
#ifndef ADCP_FRAMES_H
#define ADCP_FRAMES_H

#include <stdint.h>

/* Frame unions */



/* Frame name: NODE_A::IMU_X_RAW , Frame ID: 0 */


#ifndef IMU_X_RAW_FID 	
#define IMU_X_RAW_FID 	0
#endif

#define IMU_X_RAW_IMU_X_ACCEL_RAW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_X_RAW_IMU_X_ACCEL_RAW_START_BIT 	0
#define IMU_X_RAW_IMU_X_ACCEL_RAW_BIT_LENGTH 	16
#define IMU_X_RAW_IMU_X_ACCEL_RAW_FACTOR 	1.0f
#define IMU_X_RAW_IMU_X_ACCEL_RAW_OFFSET 	0.0f
#define IMU_X_RAW_IMU_X_ACCEL_RAW_MINIMUM 	0.0f
#define IMU_X_RAW_IMU_X_ACCEL_RAW_MAXIMUM 	65535.0f


#ifndef IMU_X_RAW_FID 	
#define IMU_X_RAW_FID 	0
#endif

#define IMU_X_RAW_IMU_X_GYRO_RAW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_X_RAW_IMU_X_GYRO_RAW_START_BIT 	16
#define IMU_X_RAW_IMU_X_GYRO_RAW_BIT_LENGTH 	16
#define IMU_X_RAW_IMU_X_GYRO_RAW_FACTOR 	1.0f
#define IMU_X_RAW_IMU_X_GYRO_RAW_OFFSET 	0.0f
#define IMU_X_RAW_IMU_X_GYRO_RAW_MINIMUM 	0.0f
#define IMU_X_RAW_IMU_X_GYRO_RAW_MAXIMUM 	65535.0f



union IMU_X_RAW_union
{
	uint32_t all;

	struct IMU_X_RAW_segments
	{
		 uint32_t IMU_X_ACCEL_RAW:16;
		 uint32_t IMU_X_GYRO_RAW:16;
	}IMU_X_RAW_segments;

}IMU_X_RAW_union;

extern union IMU_X_RAW_union IMU_X_RAW;


/* Frame name: NODE_A::IMU_Y_RAW , Frame ID: 1 */


#ifndef IMU_Y_RAW_FID 	
#define IMU_Y_RAW_FID 	1
#endif

#define IMU_Y_RAW_IMU_Y_ACCEL_RAW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_Y_RAW_IMU_Y_ACCEL_RAW_START_BIT 	0
#define IMU_Y_RAW_IMU_Y_ACCEL_RAW_BIT_LENGTH 	16
#define IMU_Y_RAW_IMU_Y_ACCEL_RAW_FACTOR 	1.0f
#define IMU_Y_RAW_IMU_Y_ACCEL_RAW_OFFSET 	0.0f
#define IMU_Y_RAW_IMU_Y_ACCEL_RAW_MINIMUM 	0.0f
#define IMU_Y_RAW_IMU_Y_ACCEL_RAW_MAXIMUM 	65535.0f


#ifndef IMU_Y_RAW_FID 	
#define IMU_Y_RAW_FID 	1
#endif

#define IMU_Y_RAW_IMU_Y_GYRO_RAW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_Y_RAW_IMU_Y_GYRO_RAW_START_BIT 	16
#define IMU_Y_RAW_IMU_Y_GYRO_RAW_BIT_LENGTH 	16
#define IMU_Y_RAW_IMU_Y_GYRO_RAW_FACTOR 	1.0f
#define IMU_Y_RAW_IMU_Y_GYRO_RAW_OFFSET 	0.0f
#define IMU_Y_RAW_IMU_Y_GYRO_RAW_MINIMUM 	0.0f
#define IMU_Y_RAW_IMU_Y_GYRO_RAW_MAXIMUM 	65535.0f



union IMU_Y_RAW_union
{
	uint32_t all;

	struct IMU_Y_RAW_segments
	{
		 uint32_t IMU_Y_ACCEL_RAW:16;
		 uint32_t IMU_Y_GYRO_RAW:16;
	}IMU_Y_RAW_segments;

}IMU_Y_RAW_union;

extern union IMU_Y_RAW_union IMU_Y_RAW;


/* Frame name: NODE_A::IMU_Z_RAW , Frame ID: 2 */


#ifndef IMU_Z_RAW_FID 	
#define IMU_Z_RAW_FID 	2
#endif

#define IMU_Z_RAW_IMU_Z_ACCEL_RAW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_Z_RAW_IMU_Z_ACCEL_RAW_START_BIT 	0
#define IMU_Z_RAW_IMU_Z_ACCEL_RAW_BIT_LENGTH 	16
#define IMU_Z_RAW_IMU_Z_ACCEL_RAW_FACTOR 	1.0f
#define IMU_Z_RAW_IMU_Z_ACCEL_RAW_OFFSET 	0.0f
#define IMU_Z_RAW_IMU_Z_ACCEL_RAW_MINIMUM 	0.0f
#define IMU_Z_RAW_IMU_Z_ACCEL_RAW_MAXIMUM 	65535.0f


#ifndef IMU_Z_RAW_FID 	
#define IMU_Z_RAW_FID 	2
#endif

#define IMU_Z_RAW_IMU_Z_GYRO_RAW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_Z_RAW_IMU_Z_GYRO_RAW_START_BIT 	16
#define IMU_Z_RAW_IMU_Z_GYRO_RAW_BIT_LENGTH 	16
#define IMU_Z_RAW_IMU_Z_GYRO_RAW_FACTOR 	1.0f
#define IMU_Z_RAW_IMU_Z_GYRO_RAW_OFFSET 	0.0f
#define IMU_Z_RAW_IMU_Z_GYRO_RAW_MINIMUM 	0.0f
#define IMU_Z_RAW_IMU_Z_GYRO_RAW_MAXIMUM 	65535.0f



union IMU_Z_RAW_union
{
	uint32_t all;

	struct IMU_Z_RAW_segments
	{
		 uint32_t IMU_Z_ACCEL_RAW:16;
		 uint32_t IMU_Z_GYRO_RAW:16;
	}IMU_Z_RAW_segments;

}IMU_Z_RAW_union;

extern union IMU_Z_RAW_union IMU_Z_RAW;


/* Frame name: NODE_A::IMU_X_PROCESSED , Frame ID: 3 */


#ifndef IMU_X_PROCESSED_FID 	
#define IMU_X_PROCESSED_FID 	3
#endif

#define IMU_X_PROCESSED_IMU_X_ACCEL_PROCESSED_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define IMU_X_PROCESSED_IMU_X_ACCEL_PROCESSED_START_BIT 	0
#define IMU_X_PROCESSED_IMU_X_ACCEL_PROCESSED_BIT_LENGTH 	16
#define IMU_X_PROCESSED_IMU_X_ACCEL_PROCESSED_FACTOR 	0.001f
#define IMU_X_PROCESSED_IMU_X_ACCEL_PROCESSED_OFFSET 	0.0f
#define IMU_X_PROCESSED_IMU_X_ACCEL_PROCESSED_MINIMUM 	-16.0f
#define IMU_X_PROCESSED_IMU_X_ACCEL_PROCESSED_MAXIMUM 	16.0f


#ifndef IMU_X_PROCESSED_FID 	
#define IMU_X_PROCESSED_FID 	3
#endif

#define IMU_X_PROCESSED_IMU_X_GYRO_PROCESSED_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define IMU_X_PROCESSED_IMU_X_GYRO_PROCESSED_START_BIT 	16
#define IMU_X_PROCESSED_IMU_X_GYRO_PROCESSED_BIT_LENGTH 	16
#define IMU_X_PROCESSED_IMU_X_GYRO_PROCESSED_FACTOR 	0.1f
#define IMU_X_PROCESSED_IMU_X_GYRO_PROCESSED_OFFSET 	0.0f
#define IMU_X_PROCESSED_IMU_X_GYRO_PROCESSED_MINIMUM 	-250.0f
#define IMU_X_PROCESSED_IMU_X_GYRO_PROCESSED_MAXIMUM 	250.0f



union IMU_X_PROCESSED_union
{
	uint32_t all;

	struct IMU_X_PROCESSED_segments
	{
		 uint32_t IMU_X_ACCEL_PROCESSED:16;
		 uint32_t IMU_X_GYRO_PROCESSED:16;
	}IMU_X_PROCESSED_segments;

}IMU_X_PROCESSED_union;

extern union IMU_X_PROCESSED_union IMU_X_PROCESSED;


/* Frame name: NODE_A::IMU_Y_PROCESSED , Frame ID: 4 */


#ifndef IMU_Y_PROCESSED_FID 	
#define IMU_Y_PROCESSED_FID 	4
#endif

#define IMU_Y_PROCESSED_IMU_Y_ACCEL_PROCESSED_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define IMU_Y_PROCESSED_IMU_Y_ACCEL_PROCESSED_START_BIT 	0
#define IMU_Y_PROCESSED_IMU_Y_ACCEL_PROCESSED_BIT_LENGTH 	16
#define IMU_Y_PROCESSED_IMU_Y_ACCEL_PROCESSED_FACTOR 	0.001f
#define IMU_Y_PROCESSED_IMU_Y_ACCEL_PROCESSED_OFFSET 	0.0f
#define IMU_Y_PROCESSED_IMU_Y_ACCEL_PROCESSED_MINIMUM 	-16.0f
#define IMU_Y_PROCESSED_IMU_Y_ACCEL_PROCESSED_MAXIMUM 	16.0f


#ifndef IMU_Y_PROCESSED_FID 	
#define IMU_Y_PROCESSED_FID 	4
#endif

#define IMU_Y_PROCESSED_IMU_Y_GYRO_PROCESSED_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define IMU_Y_PROCESSED_IMU_Y_GYRO_PROCESSED_START_BIT 	16
#define IMU_Y_PROCESSED_IMU_Y_GYRO_PROCESSED_BIT_LENGTH 	16
#define IMU_Y_PROCESSED_IMU_Y_GYRO_PROCESSED_FACTOR 	0.1f
#define IMU_Y_PROCESSED_IMU_Y_GYRO_PROCESSED_OFFSET 	0.0f
#define IMU_Y_PROCESSED_IMU_Y_GYRO_PROCESSED_MINIMUM 	-250.0f
#define IMU_Y_PROCESSED_IMU_Y_GYRO_PROCESSED_MAXIMUM 	250.0f



union IMU_Y_PROCESSED_union
{
	uint32_t all;

	struct IMU_Y_PROCESSED_segments
	{
		 uint32_t IMU_Y_ACCEL_PROCESSED:16;
		 uint32_t IMU_Y_GYRO_PROCESSED:16;
	}IMU_Y_PROCESSED_segments;

}IMU_Y_PROCESSED_union;

extern union IMU_Y_PROCESSED_union IMU_Y_PROCESSED;


/* Frame name: NODE_A::IMU_Z_PROCESSED , Frame ID: 5 */


#ifndef IMU_Z_PROCESSED_FID 	
#define IMU_Z_PROCESSED_FID 	5
#endif

#define IMU_Z_PROCESSED_IMU_Z_ACCEL_PROCESSED_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define IMU_Z_PROCESSED_IMU_Z_ACCEL_PROCESSED_START_BIT 	0
#define IMU_Z_PROCESSED_IMU_Z_ACCEL_PROCESSED_BIT_LENGTH 	16
#define IMU_Z_PROCESSED_IMU_Z_ACCEL_PROCESSED_FACTOR 	0.001f
#define IMU_Z_PROCESSED_IMU_Z_ACCEL_PROCESSED_OFFSET 	0.0f
#define IMU_Z_PROCESSED_IMU_Z_ACCEL_PROCESSED_MINIMUM 	-16.0f
#define IMU_Z_PROCESSED_IMU_Z_ACCEL_PROCESSED_MAXIMUM 	16.0f


#ifndef IMU_Z_PROCESSED_FID 	
#define IMU_Z_PROCESSED_FID 	5
#endif

#define IMU_Z_PROCESSED_IMU_Z_GYRO_PROCESSED_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define IMU_Z_PROCESSED_IMU_Z_GYRO_PROCESSED_START_BIT 	16
#define IMU_Z_PROCESSED_IMU_Z_GYRO_PROCESSED_BIT_LENGTH 	16
#define IMU_Z_PROCESSED_IMU_Z_GYRO_PROCESSED_FACTOR 	0.1f
#define IMU_Z_PROCESSED_IMU_Z_GYRO_PROCESSED_OFFSET 	0.0f
#define IMU_Z_PROCESSED_IMU_Z_GYRO_PROCESSED_MINIMUM 	-250.0f
#define IMU_Z_PROCESSED_IMU_Z_GYRO_PROCESSED_MAXIMUM 	250.0f



union IMU_Z_PROCESSED_union
{
	uint32_t all;

	struct IMU_Z_PROCESSED_segments
	{
		 uint32_t IMU_Z_ACCEL_PROCESSED:16;
		 uint32_t IMU_Z_GYRO_PROCESSED:16;
	}IMU_Z_PROCESSED_segments;

}IMU_Z_PROCESSED_union;

extern union IMU_Z_PROCESSED_union IMU_Z_PROCESSED;


/* Frame name: NODE_A::IMU_CONFIG_REG_A , Frame ID: 6 */


#ifndef IMU_CONFIG_REG_A_FID 	
#define IMU_CONFIG_REG_A_FID 	6
#endif

#define IMU_CONFIG_REG_A_IMU_CONFIG_SAMPLING_RATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_REG_A_IMU_CONFIG_SAMPLING_RATE_START_BIT 	16
#define IMU_CONFIG_REG_A_IMU_CONFIG_SAMPLING_RATE_BIT_LENGTH 	16
#define IMU_CONFIG_REG_A_IMU_CONFIG_SAMPLING_RATE_FACTOR 	1.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_SAMPLING_RATE_OFFSET 	0.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_SAMPLING_RATE_MINIMUM 	20.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_SAMPLING_RATE_MAXIMUM 	500.0f


#ifndef IMU_CONFIG_REG_A_FID 	
#define IMU_CONFIG_REG_A_FID 	6
#endif

#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_INTERVAL_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_INTERVAL_START_BIT 	8
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_INTERVAL_BIT_LENGTH 	8
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_INTERVAL_FACTOR 	1.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_INTERVAL_OFFSET 	0.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_INTERVAL_MINIMUM 	0.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_INTERVAL_MAXIMUM 	250.0f


#ifndef IMU_CONFIG_REG_A_FID 	
#define IMU_CONFIG_REG_A_FID 	6
#endif

#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_POINTS_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_POINTS_START_BIT 	0
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_POINTS_BIT_LENGTH 	8
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_POINTS_FACTOR 	1.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_POINTS_OFFSET 	0.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_POINTS_MINIMUM 	0.0f
#define IMU_CONFIG_REG_A_IMU_CONFIG_CALIB_POINTS_MAXIMUM 	250.0f



union IMU_CONFIG_REG_A_union
{
	uint32_t all;

	struct IMU_CONFIG_REG_A_segments
	{
		 uint32_t IMU_CONFIG_SAMPLING_RATE:16;
		 uint32_t IMU_CONFIG_CALIB_INTERVAL:8;
		 uint32_t IMU_CONFIG_CALIB_POINTS:8;
	}IMU_CONFIG_REG_A_segments;

}IMU_CONFIG_REG_A_union;

extern union IMU_CONFIG_REG_A_union IMU_CONFIG_REG_A;


/* Frame name: NODE_A::IMU_CONFIG_REG_B , Frame ID: 7 */


#ifndef IMU_CONFIG_REG_B_FID 	
#define IMU_CONFIG_REG_B_FID 	7
#endif

#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_BW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_BW_START_BIT 	0
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_BW_BIT_LENGTH 	3
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_BW_FACTOR 	1.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_BW_OFFSET 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_BW_MINIMUM 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_BW_MAXIMUM 	7.0f


#ifndef IMU_CONFIG_REG_B_FID 	
#define IMU_CONFIG_REG_B_FID 	7
#endif

#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_BW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_BW_START_BIT 	3
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_BW_BIT_LENGTH 	3
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_BW_FACTOR 	1.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_BW_OFFSET 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_BW_MINIMUM 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_BW_MAXIMUM 	7.0f


#ifndef IMU_CONFIG_REG_B_FID 	
#define IMU_CONFIG_REG_B_FID 	7
#endif

#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_FS_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_FS_START_BIT 	6
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_FS_BIT_LENGTH 	3
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_FS_FACTOR 	1.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_FS_OFFSET 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_FS_MINIMUM 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_GYRO_FS_MAXIMUM 	7.0f


#ifndef IMU_CONFIG_REG_B_FID 	
#define IMU_CONFIG_REG_B_FID 	7
#endif

#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_FS_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_FS_START_BIT 	9
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_FS_BIT_LENGTH 	3
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_FS_FACTOR 	1.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_FS_OFFSET 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_FS_MINIMUM 	0.0f
#define IMU_CONFIG_REG_B_IMU_CONFIG_ACCEL_FS_MAXIMUM 	7.0f



union IMU_CONFIG_REG_B_union
{
	uint32_t all;

	struct IMU_CONFIG_REG_B_segments
	{
		 uint32_t IMU_CONFIG_GYRO_BW:3;
		 uint32_t IMU_CONFIG_ACCEL_BW:3;
		 uint32_t IMU_CONFIG_GYRO_FS:3;
		 uint32_t IMU_CONFIG_ACCEL_FS:3;
	}IMU_CONFIG_REG_B_segments;

}IMU_CONFIG_REG_B_union;

extern union IMU_CONFIG_REG_B_union IMU_CONFIG_REG_B;


/* Frame name: NODE_A::IMU_CONFIG_WRITE_ENABLE , Frame ID: 8 */


#ifndef IMU_CONFIG_WRITE_ENABLE_FID 	
#define IMU_CONFIG_WRITE_ENABLE_FID 	8
#endif

#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_SAMPLING_RATE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_SAMPLING_RATE_WE_START_BIT 	0
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_SAMPLING_RATE_WE_BIT_LENGTH 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_SAMPLING_RATE_WE_FACTOR 	1.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_SAMPLING_RATE_WE_OFFSET 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_SAMPLING_RATE_WE_MINIMUM 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_SAMPLING_RATE_WE_MAXIMUM 	1.0f


#ifndef IMU_CONFIG_WRITE_ENABLE_FID 	
#define IMU_CONFIG_WRITE_ENABLE_FID 	8
#endif

#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_INTERVAL_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_INTERVAL_WE_START_BIT 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_INTERVAL_WE_BIT_LENGTH 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_INTERVAL_WE_FACTOR 	1.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_INTERVAL_WE_OFFSET 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_INTERVAL_WE_MINIMUM 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_INTERVAL_WE_MAXIMUM 	1.0f


#ifndef IMU_CONFIG_WRITE_ENABLE_FID 	
#define IMU_CONFIG_WRITE_ENABLE_FID 	8
#endif

#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_POINTS_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_POINTS_WE_START_BIT 	2
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_POINTS_WE_BIT_LENGTH 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_POINTS_WE_FACTOR 	1.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_POINTS_WE_OFFSET 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_POINTS_WE_MINIMUM 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_CALIB_POINTS_WE_MAXIMUM 	1.0f


#ifndef IMU_CONFIG_WRITE_ENABLE_FID 	
#define IMU_CONFIG_WRITE_ENABLE_FID 	8
#endif

#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_BW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_BW_WE_START_BIT 	3
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_BW_WE_BIT_LENGTH 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_BW_WE_FACTOR 	1.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_BW_WE_OFFSET 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_BW_WE_MINIMUM 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_BW_WE_MAXIMUM 	1.0f


#ifndef IMU_CONFIG_WRITE_ENABLE_FID 	
#define IMU_CONFIG_WRITE_ENABLE_FID 	8
#endif

#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_BW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_BW_WE_START_BIT 	4
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_BW_WE_BIT_LENGTH 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_BW_WE_FACTOR 	1.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_BW_WE_OFFSET 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_BW_WE_MINIMUM 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_BW_WE_MAXIMUM 	1.0f


#ifndef IMU_CONFIG_WRITE_ENABLE_FID 	
#define IMU_CONFIG_WRITE_ENABLE_FID 	8
#endif

#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_FS_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_FS_WE_START_BIT 	5
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_FS_WE_BIT_LENGTH 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_FS_WE_FACTOR 	1.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_FS_WE_OFFSET 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_FS_WE_MINIMUM 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_GYRO_FS_WE_MAXIMUM 	1.0f


#ifndef IMU_CONFIG_WRITE_ENABLE_FID 	
#define IMU_CONFIG_WRITE_ENABLE_FID 	8
#endif

#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_FS_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_FS_WE_START_BIT 	6
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_FS_WE_BIT_LENGTH 	1
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_FS_WE_FACTOR 	1.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_FS_WE_OFFSET 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_FS_WE_MINIMUM 	0.0f
#define IMU_CONFIG_WRITE_ENABLE_IMU_CONFIG_ACCEL_FS_WE_MAXIMUM 	1.0f



union IMU_CONFIG_WRITE_ENABLE_union
{
	uint32_t all;

	struct IMU_CONFIG_WRITE_ENABLE_segments
	{
		 uint32_t IMU_CONFIG_SAMPLING_RATE_WE:1;
		 uint32_t IMU_CONFIG_CALIB_INTERVAL_WE:1;
		 uint32_t IMU_CONFIG_CALIB_POINTS_WE:1;
		 uint32_t IMU_CONFIG_GYRO_BW_WE:1;
		 uint32_t IMU_CONFIG_ACCEL_BW_WE:1;
		 uint32_t IMU_CONFIG_GYRO_FS_WE:1;
		 uint32_t IMU_CONFIG_ACCEL_FS_WE:1;
	}IMU_CONFIG_WRITE_ENABLE_segments;

}IMU_CONFIG_WRITE_ENABLE_union;

extern union IMU_CONFIG_WRITE_ENABLE_union IMU_CONFIG_WRITE_ENABLE;


/* Frame name: NODE_A::MD_THRESHOLD_TYPE , Frame ID: 9 */


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_ACCEL_X_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_ACCEL_X_THRESHOLD_TYPE_START_BIT 	0
#define MD_THRESHOLD_TYPE_MD_ACCEL_X_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_ACCEL_X_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_X_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_X_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_X_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_ACCEL_Y_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_ACCEL_Y_THRESHOLD_TYPE_START_BIT 	3
#define MD_THRESHOLD_TYPE_MD_ACCEL_Y_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_ACCEL_Y_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_Y_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_Y_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_Y_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_ACCEL_Z_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_ACCEL_Z_THRESHOLD_TYPE_START_BIT 	6
#define MD_THRESHOLD_TYPE_MD_ACCEL_Z_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_ACCEL_Z_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_Z_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_Z_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_ACCEL_Z_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_GYRO_X_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_GYRO_X_THRESHOLD_TYPE_START_BIT 	9
#define MD_THRESHOLD_TYPE_MD_GYRO_X_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_GYRO_X_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_X_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_X_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_X_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_GYRO_Y_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_GYRO_Y_THRESHOLD_TYPE_START_BIT 	12
#define MD_THRESHOLD_TYPE_MD_GYRO_Y_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_GYRO_Y_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_Y_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_Y_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_Y_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_GYRO_Z_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_GYRO_Z_THRESHOLD_TYPE_START_BIT 	15
#define MD_THRESHOLD_TYPE_MD_GYRO_Z_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_GYRO_Z_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_Z_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_Z_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_GYRO_Z_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_ROLL_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_ROLL_THRESHOLD_TYPE_START_BIT 	18
#define MD_THRESHOLD_TYPE_MD_ROLL_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_ROLL_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_ROLL_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_ROLL_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_ROLL_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_PITCH_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_PITCH_THRESHOLD_TYPE_START_BIT 	21
#define MD_THRESHOLD_TYPE_MD_PITCH_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_PITCH_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_PITCH_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_PITCH_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_PITCH_THRESHOLD_TYPE_MAXIMUM 	7.0f


#ifndef MD_THRESHOLD_TYPE_FID 	
#define MD_THRESHOLD_TYPE_FID 	9
#endif

#define MD_THRESHOLD_TYPE_MD_YAW_THRESHOLD_TYPE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_THRESHOLD_TYPE_MD_YAW_THRESHOLD_TYPE_START_BIT 	24
#define MD_THRESHOLD_TYPE_MD_YAW_THRESHOLD_TYPE_BIT_LENGTH 	3
#define MD_THRESHOLD_TYPE_MD_YAW_THRESHOLD_TYPE_FACTOR 	1.0f
#define MD_THRESHOLD_TYPE_MD_YAW_THRESHOLD_TYPE_OFFSET 	0.0f
#define MD_THRESHOLD_TYPE_MD_YAW_THRESHOLD_TYPE_MINIMUM 	0.0f
#define MD_THRESHOLD_TYPE_MD_YAW_THRESHOLD_TYPE_MAXIMUM 	7.0f



union MD_THRESHOLD_TYPE_union
{
	uint32_t all;

	struct MD_THRESHOLD_TYPE_segments
	{
		 uint32_t MD_ACCEL_X_THRESHOLD_TYPE:3;
		 uint32_t MD_ACCEL_Y_THRESHOLD_TYPE:3;
		 uint32_t MD_ACCEL_Z_THRESHOLD_TYPE:3;
		 uint32_t MD_GYRO_X_THRESHOLD_TYPE:3;
		 uint32_t MD_GYRO_Y_THRESHOLD_TYPE:3;
		 uint32_t MD_GYRO_Z_THRESHOLD_TYPE:3;
		 uint32_t MD_ROLL_THRESHOLD_TYPE:3;
		 uint32_t MD_PITCH_THRESHOLD_TYPE:3;
		 uint32_t MD_YAW_THRESHOLD_TYPE:3;
	}MD_THRESHOLD_TYPE_segments;

}MD_THRESHOLD_TYPE_union;

extern union MD_THRESHOLD_TYPE_union MD_THRESHOLD_TYPE;


/* Frame name: NODE_A::MD_ACCEL_X_THRESHOLD_LOW , Frame ID: 10 */


#ifndef MD_ACCEL_X_THRESHOLD_LOW_FID 	
#define MD_ACCEL_X_THRESHOLD_LOW_FID 	10
#endif

#define MD_ACCEL_X_THRESHOLD_LOW_MD_ACCEL_X_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ACCEL_X_THRESHOLD_LOW_MD_ACCEL_X_THRESHOLD_LOW_START_BIT 	0
#define MD_ACCEL_X_THRESHOLD_LOW_MD_ACCEL_X_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_ACCEL_X_THRESHOLD_LOW_MD_ACCEL_X_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_ACCEL_X_THRESHOLD_LOW_MD_ACCEL_X_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_ACCEL_X_THRESHOLD_LOW_MD_ACCEL_X_THRESHOLD_LOW_MINIMUM 	-16.0f
#define MD_ACCEL_X_THRESHOLD_LOW_MD_ACCEL_X_THRESHOLD_LOW_MAXIMUM 	16.0f



union MD_ACCEL_X_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_ACCEL_X_THRESHOLD_LOW_segments
	{
		 uint32_t MD_ACCEL_X_THRESHOLD_LOW:32;
	}MD_ACCEL_X_THRESHOLD_LOW_segments;

}MD_ACCEL_X_THRESHOLD_LOW_union;

extern union MD_ACCEL_X_THRESHOLD_LOW_union MD_ACCEL_X_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_ACCEL_X_THRESHOLD_HIGH , Frame ID: 11 */


#ifndef MD_ACCEL_X_THRESHOLD_HIGH_FID 	
#define MD_ACCEL_X_THRESHOLD_HIGH_FID 	11
#endif

#define MD_ACCEL_X_THRESHOLD_HIGH_MD_ACCEL_X_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ACCEL_X_THRESHOLD_HIGH_MD_ACCEL_X_THRESHOLD_HIGH_START_BIT 	0
#define MD_ACCEL_X_THRESHOLD_HIGH_MD_ACCEL_X_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_ACCEL_X_THRESHOLD_HIGH_MD_ACCEL_X_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_ACCEL_X_THRESHOLD_HIGH_MD_ACCEL_X_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_ACCEL_X_THRESHOLD_HIGH_MD_ACCEL_X_THRESHOLD_HIGH_MINIMUM 	-16.0f
#define MD_ACCEL_X_THRESHOLD_HIGH_MD_ACCEL_X_THRESHOLD_HIGH_MAXIMUM 	16.0f



union MD_ACCEL_X_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_ACCEL_X_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_ACCEL_X_THRESHOLD_HIGH:32;
	}MD_ACCEL_X_THRESHOLD_HIGH_segments;

}MD_ACCEL_X_THRESHOLD_HIGH_union;

extern union MD_ACCEL_X_THRESHOLD_HIGH_union MD_ACCEL_X_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_ACCEL_Y_THRESHOLD_LOW , Frame ID: 12 */


#ifndef MD_ACCEL_Y_THRESHOLD_LOW_FID 	
#define MD_ACCEL_Y_THRESHOLD_LOW_FID 	12
#endif

#define MD_ACCEL_Y_THRESHOLD_LOW_MD_ACCEL_Y_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ACCEL_Y_THRESHOLD_LOW_MD_ACCEL_Y_THRESHOLD_LOW_START_BIT 	0
#define MD_ACCEL_Y_THRESHOLD_LOW_MD_ACCEL_Y_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_ACCEL_Y_THRESHOLD_LOW_MD_ACCEL_Y_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_ACCEL_Y_THRESHOLD_LOW_MD_ACCEL_Y_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_ACCEL_Y_THRESHOLD_LOW_MD_ACCEL_Y_THRESHOLD_LOW_MINIMUM 	-16.0f
#define MD_ACCEL_Y_THRESHOLD_LOW_MD_ACCEL_Y_THRESHOLD_LOW_MAXIMUM 	16.0f



union MD_ACCEL_Y_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_ACCEL_Y_THRESHOLD_LOW_segments
	{
		 uint32_t MD_ACCEL_Y_THRESHOLD_LOW:32;
	}MD_ACCEL_Y_THRESHOLD_LOW_segments;

}MD_ACCEL_Y_THRESHOLD_LOW_union;

extern union MD_ACCEL_Y_THRESHOLD_LOW_union MD_ACCEL_Y_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_ACCEL_Y_THRESHOLD_HIGH , Frame ID: 13 */


#ifndef MD_ACCEL_Y_THRESHOLD_HIGH_FID 	
#define MD_ACCEL_Y_THRESHOLD_HIGH_FID 	13
#endif

#define MD_ACCEL_Y_THRESHOLD_HIGH_MD_ACCEL_Y_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ACCEL_Y_THRESHOLD_HIGH_MD_ACCEL_Y_THRESHOLD_HIGH_START_BIT 	0
#define MD_ACCEL_Y_THRESHOLD_HIGH_MD_ACCEL_Y_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_ACCEL_Y_THRESHOLD_HIGH_MD_ACCEL_Y_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_ACCEL_Y_THRESHOLD_HIGH_MD_ACCEL_Y_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_ACCEL_Y_THRESHOLD_HIGH_MD_ACCEL_Y_THRESHOLD_HIGH_MINIMUM 	-16.0f
#define MD_ACCEL_Y_THRESHOLD_HIGH_MD_ACCEL_Y_THRESHOLD_HIGH_MAXIMUM 	16.0f



union MD_ACCEL_Y_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_ACCEL_Y_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_ACCEL_Y_THRESHOLD_HIGH:32;
	}MD_ACCEL_Y_THRESHOLD_HIGH_segments;

}MD_ACCEL_Y_THRESHOLD_HIGH_union;

extern union MD_ACCEL_Y_THRESHOLD_HIGH_union MD_ACCEL_Y_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_ACCEL_Z_THRESHOLD_LOW , Frame ID: 14 */


#ifndef MD_ACCEL_Z_THRESHOLD_LOW_FID 	
#define MD_ACCEL_Z_THRESHOLD_LOW_FID 	14
#endif

#define MD_ACCEL_Z_THRESHOLD_LOW_MD_ACCEL_Z_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ACCEL_Z_THRESHOLD_LOW_MD_ACCEL_Z_THRESHOLD_LOW_START_BIT 	0
#define MD_ACCEL_Z_THRESHOLD_LOW_MD_ACCEL_Z_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_ACCEL_Z_THRESHOLD_LOW_MD_ACCEL_Z_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_ACCEL_Z_THRESHOLD_LOW_MD_ACCEL_Z_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_ACCEL_Z_THRESHOLD_LOW_MD_ACCEL_Z_THRESHOLD_LOW_MINIMUM 	-16.0f
#define MD_ACCEL_Z_THRESHOLD_LOW_MD_ACCEL_Z_THRESHOLD_LOW_MAXIMUM 	16.0f



union MD_ACCEL_Z_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_ACCEL_Z_THRESHOLD_LOW_segments
	{
		 uint32_t MD_ACCEL_Z_THRESHOLD_LOW:32;
	}MD_ACCEL_Z_THRESHOLD_LOW_segments;

}MD_ACCEL_Z_THRESHOLD_LOW_union;

extern union MD_ACCEL_Z_THRESHOLD_LOW_union MD_ACCEL_Z_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_ACCEL_Z_THRESHOLD_HIGH , Frame ID: 15 */


#ifndef MD_ACCEL_Z_THRESHOLD_HIGH_FID 	
#define MD_ACCEL_Z_THRESHOLD_HIGH_FID 	15
#endif

#define MD_ACCEL_Z_THRESHOLD_HIGH_MD_ACCEL_Z_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ACCEL_Z_THRESHOLD_HIGH_MD_ACCEL_Z_THRESHOLD_HIGH_START_BIT 	0
#define MD_ACCEL_Z_THRESHOLD_HIGH_MD_ACCEL_Z_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_ACCEL_Z_THRESHOLD_HIGH_MD_ACCEL_Z_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_ACCEL_Z_THRESHOLD_HIGH_MD_ACCEL_Z_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_ACCEL_Z_THRESHOLD_HIGH_MD_ACCEL_Z_THRESHOLD_HIGH_MINIMUM 	-16.0f
#define MD_ACCEL_Z_THRESHOLD_HIGH_MD_ACCEL_Z_THRESHOLD_HIGH_MAXIMUM 	16.0f



union MD_ACCEL_Z_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_ACCEL_Z_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_ACCEL_Z_THRESHOLD_HIGH:32;
	}MD_ACCEL_Z_THRESHOLD_HIGH_segments;

}MD_ACCEL_Z_THRESHOLD_HIGH_union;

extern union MD_ACCEL_Z_THRESHOLD_HIGH_union MD_ACCEL_Z_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_GYRO_X_THRESHOLD_LOW , Frame ID: 16 */


#ifndef MD_GYRO_X_THRESHOLD_LOW_FID 	
#define MD_GYRO_X_THRESHOLD_LOW_FID 	16
#endif

#define MD_GYRO_X_THRESHOLD_LOW_MD_GYRO_X_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_GYRO_X_THRESHOLD_LOW_MD_GYRO_X_THRESHOLD_LOW_START_BIT 	0
#define MD_GYRO_X_THRESHOLD_LOW_MD_GYRO_X_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_GYRO_X_THRESHOLD_LOW_MD_GYRO_X_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_GYRO_X_THRESHOLD_LOW_MD_GYRO_X_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_GYRO_X_THRESHOLD_LOW_MD_GYRO_X_THRESHOLD_LOW_MINIMUM 	-2000.0f
#define MD_GYRO_X_THRESHOLD_LOW_MD_GYRO_X_THRESHOLD_LOW_MAXIMUM 	2000.0f



union MD_GYRO_X_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_GYRO_X_THRESHOLD_LOW_segments
	{
		 uint32_t MD_GYRO_X_THRESHOLD_LOW:32;
	}MD_GYRO_X_THRESHOLD_LOW_segments;

}MD_GYRO_X_THRESHOLD_LOW_union;

extern union MD_GYRO_X_THRESHOLD_LOW_union MD_GYRO_X_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_GYRO_X_THRESHOLD_HIGH , Frame ID: 17 */


#ifndef MD_GYRO_X_THRESHOLD_HIGH_FID 	
#define MD_GYRO_X_THRESHOLD_HIGH_FID 	17
#endif

#define MD_GYRO_X_THRESHOLD_HIGH_MD_GYRO_X_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_GYRO_X_THRESHOLD_HIGH_MD_GYRO_X_THRESHOLD_HIGH_START_BIT 	0
#define MD_GYRO_X_THRESHOLD_HIGH_MD_GYRO_X_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_GYRO_X_THRESHOLD_HIGH_MD_GYRO_X_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_GYRO_X_THRESHOLD_HIGH_MD_GYRO_X_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_GYRO_X_THRESHOLD_HIGH_MD_GYRO_X_THRESHOLD_HIGH_MINIMUM 	-2000.0f
#define MD_GYRO_X_THRESHOLD_HIGH_MD_GYRO_X_THRESHOLD_HIGH_MAXIMUM 	2000.0f



union MD_GYRO_X_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_GYRO_X_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_GYRO_X_THRESHOLD_HIGH:32;
	}MD_GYRO_X_THRESHOLD_HIGH_segments;

}MD_GYRO_X_THRESHOLD_HIGH_union;

extern union MD_GYRO_X_THRESHOLD_HIGH_union MD_GYRO_X_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_GYRO_Y_THRESHOLD_LOW , Frame ID: 18 */


#ifndef MD_GYRO_Y_THRESHOLD_LOW_FID 	
#define MD_GYRO_Y_THRESHOLD_LOW_FID 	18
#endif

#define MD_GYRO_Y_THRESHOLD_LOW_MD_GYRO_Y_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_GYRO_Y_THRESHOLD_LOW_MD_GYRO_Y_THRESHOLD_LOW_START_BIT 	0
#define MD_GYRO_Y_THRESHOLD_LOW_MD_GYRO_Y_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_GYRO_Y_THRESHOLD_LOW_MD_GYRO_Y_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_GYRO_Y_THRESHOLD_LOW_MD_GYRO_Y_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_GYRO_Y_THRESHOLD_LOW_MD_GYRO_Y_THRESHOLD_LOW_MINIMUM 	-2000.0f
#define MD_GYRO_Y_THRESHOLD_LOW_MD_GYRO_Y_THRESHOLD_LOW_MAXIMUM 	2000.0f



union MD_GYRO_Y_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_GYRO_Y_THRESHOLD_LOW_segments
	{
		 uint32_t MD_GYRO_Y_THRESHOLD_LOW:32;
	}MD_GYRO_Y_THRESHOLD_LOW_segments;

}MD_GYRO_Y_THRESHOLD_LOW_union;

extern union MD_GYRO_Y_THRESHOLD_LOW_union MD_GYRO_Y_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_GYRO_Y_THRESHOLD_HIGH , Frame ID: 19 */


#ifndef MD_GYRO_Y_THRESHOLD_HIGH_FID 	
#define MD_GYRO_Y_THRESHOLD_HIGH_FID 	19
#endif

#define MD_GYRO_Y_THRESHOLD_HIGH_MD_GYRO_Y_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_GYRO_Y_THRESHOLD_HIGH_MD_GYRO_Y_THRESHOLD_HIGH_START_BIT 	0
#define MD_GYRO_Y_THRESHOLD_HIGH_MD_GYRO_Y_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_GYRO_Y_THRESHOLD_HIGH_MD_GYRO_Y_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_GYRO_Y_THRESHOLD_HIGH_MD_GYRO_Y_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_GYRO_Y_THRESHOLD_HIGH_MD_GYRO_Y_THRESHOLD_HIGH_MINIMUM 	-2000.0f
#define MD_GYRO_Y_THRESHOLD_HIGH_MD_GYRO_Y_THRESHOLD_HIGH_MAXIMUM 	2000.0f



union MD_GYRO_Y_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_GYRO_Y_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_GYRO_Y_THRESHOLD_HIGH:32;
	}MD_GYRO_Y_THRESHOLD_HIGH_segments;

}MD_GYRO_Y_THRESHOLD_HIGH_union;

extern union MD_GYRO_Y_THRESHOLD_HIGH_union MD_GYRO_Y_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_GYRO_Z_THRESHOLD_LOW , Frame ID: 20 */


#ifndef MD_GYRO_Z_THRESHOLD_LOW_FID 	
#define MD_GYRO_Z_THRESHOLD_LOW_FID 	20
#endif

#define MD_GYRO_Z_THRESHOLD_LOW_MD_GYRO_Z_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_GYRO_Z_THRESHOLD_LOW_MD_GYRO_Z_THRESHOLD_LOW_START_BIT 	0
#define MD_GYRO_Z_THRESHOLD_LOW_MD_GYRO_Z_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_GYRO_Z_THRESHOLD_LOW_MD_GYRO_Z_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_GYRO_Z_THRESHOLD_LOW_MD_GYRO_Z_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_GYRO_Z_THRESHOLD_LOW_MD_GYRO_Z_THRESHOLD_LOW_MINIMUM 	-2000.0f
#define MD_GYRO_Z_THRESHOLD_LOW_MD_GYRO_Z_THRESHOLD_LOW_MAXIMUM 	2000.0f



union MD_GYRO_Z_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_GYRO_Z_THRESHOLD_LOW_segments
	{
		 uint32_t MD_GYRO_Z_THRESHOLD_LOW:32;
	}MD_GYRO_Z_THRESHOLD_LOW_segments;

}MD_GYRO_Z_THRESHOLD_LOW_union;

extern union MD_GYRO_Z_THRESHOLD_LOW_union MD_GYRO_Z_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_GYRO_Z_THRESHOLD_HIGH , Frame ID: 21 */


#ifndef MD_GYRO_Z_THRESHOLD_HIGH_FID 	
#define MD_GYRO_Z_THRESHOLD_HIGH_FID 	21
#endif

#define MD_GYRO_Z_THRESHOLD_HIGH_MD_GYRO_Z_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_GYRO_Z_THRESHOLD_HIGH_MD_GYRO_Z_THRESHOLD_HIGH_START_BIT 	0
#define MD_GYRO_Z_THRESHOLD_HIGH_MD_GYRO_Z_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_GYRO_Z_THRESHOLD_HIGH_MD_GYRO_Z_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_GYRO_Z_THRESHOLD_HIGH_MD_GYRO_Z_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_GYRO_Z_THRESHOLD_HIGH_MD_GYRO_Z_THRESHOLD_HIGH_MINIMUM 	-2000.0f
#define MD_GYRO_Z_THRESHOLD_HIGH_MD_GYRO_Z_THRESHOLD_HIGH_MAXIMUM 	2000.0f



union MD_GYRO_Z_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_GYRO_Z_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_GYRO_Z_THRESHOLD_HIGH:32;
	}MD_GYRO_Z_THRESHOLD_HIGH_segments;

}MD_GYRO_Z_THRESHOLD_HIGH_union;

extern union MD_GYRO_Z_THRESHOLD_HIGH_union MD_GYRO_Z_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_ROLL_THRESHOLD_LOW , Frame ID: 22 */


#ifndef MD_ROLL_THRESHOLD_LOW_FID 	
#define MD_ROLL_THRESHOLD_LOW_FID 	22
#endif

#define MD_ROLL_THRESHOLD_LOW_MD_ROLL_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ROLL_THRESHOLD_LOW_MD_ROLL_THRESHOLD_LOW_START_BIT 	0
#define MD_ROLL_THRESHOLD_LOW_MD_ROLL_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_ROLL_THRESHOLD_LOW_MD_ROLL_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_ROLL_THRESHOLD_LOW_MD_ROLL_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_ROLL_THRESHOLD_LOW_MD_ROLL_THRESHOLD_LOW_MINIMUM 	-180.0f
#define MD_ROLL_THRESHOLD_LOW_MD_ROLL_THRESHOLD_LOW_MAXIMUM 	180.0f



union MD_ROLL_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_ROLL_THRESHOLD_LOW_segments
	{
		 uint32_t MD_ROLL_THRESHOLD_LOW:32;
	}MD_ROLL_THRESHOLD_LOW_segments;

}MD_ROLL_THRESHOLD_LOW_union;

extern union MD_ROLL_THRESHOLD_LOW_union MD_ROLL_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_ROLL_THRESHOLD_HIGH , Frame ID: 23 */


#ifndef MD_ROLL_THRESHOLD_HIGH_FID 	
#define MD_ROLL_THRESHOLD_HIGH_FID 	23
#endif

#define MD_ROLL_THRESHOLD_HIGH_MD_ROLL_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_ROLL_THRESHOLD_HIGH_MD_ROLL_THRESHOLD_HIGH_START_BIT 	0
#define MD_ROLL_THRESHOLD_HIGH_MD_ROLL_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_ROLL_THRESHOLD_HIGH_MD_ROLL_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_ROLL_THRESHOLD_HIGH_MD_ROLL_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_ROLL_THRESHOLD_HIGH_MD_ROLL_THRESHOLD_HIGH_MINIMUM 	-180.0f
#define MD_ROLL_THRESHOLD_HIGH_MD_ROLL_THRESHOLD_HIGH_MAXIMUM 	180.0f



union MD_ROLL_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_ROLL_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_ROLL_THRESHOLD_HIGH:32;
	}MD_ROLL_THRESHOLD_HIGH_segments;

}MD_ROLL_THRESHOLD_HIGH_union;

extern union MD_ROLL_THRESHOLD_HIGH_union MD_ROLL_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_PITCH_THRESHOLD_LOW , Frame ID: 24 */


#ifndef MD_PITCH_THRESHOLD_LOW_FID 	
#define MD_PITCH_THRESHOLD_LOW_FID 	24
#endif

#define MD_PITCH_THRESHOLD_LOW_MD_PITCH_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_PITCH_THRESHOLD_LOW_MD_PITCH_THRESHOLD_LOW_START_BIT 	0
#define MD_PITCH_THRESHOLD_LOW_MD_PITCH_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_PITCH_THRESHOLD_LOW_MD_PITCH_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_PITCH_THRESHOLD_LOW_MD_PITCH_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_PITCH_THRESHOLD_LOW_MD_PITCH_THRESHOLD_LOW_MINIMUM 	-180.0f
#define MD_PITCH_THRESHOLD_LOW_MD_PITCH_THRESHOLD_LOW_MAXIMUM 	180.0f



union MD_PITCH_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_PITCH_THRESHOLD_LOW_segments
	{
		 uint32_t MD_PITCH_THRESHOLD_LOW:32;
	}MD_PITCH_THRESHOLD_LOW_segments;

}MD_PITCH_THRESHOLD_LOW_union;

extern union MD_PITCH_THRESHOLD_LOW_union MD_PITCH_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_PITCH_THRESHOLD_HIGH , Frame ID: 25 */


#ifndef MD_PITCH_THRESHOLD_HIGH_FID 	
#define MD_PITCH_THRESHOLD_HIGH_FID 	25
#endif

#define MD_PITCH_THRESHOLD_HIGH_MD_PITCH_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_PITCH_THRESHOLD_HIGH_MD_PITCH_THRESHOLD_HIGH_START_BIT 	0
#define MD_PITCH_THRESHOLD_HIGH_MD_PITCH_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_PITCH_THRESHOLD_HIGH_MD_PITCH_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_PITCH_THRESHOLD_HIGH_MD_PITCH_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_PITCH_THRESHOLD_HIGH_MD_PITCH_THRESHOLD_HIGH_MINIMUM 	-180.0f
#define MD_PITCH_THRESHOLD_HIGH_MD_PITCH_THRESHOLD_HIGH_MAXIMUM 	180.0f



union MD_PITCH_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_PITCH_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_PITCH_THRESHOLD_HIGH:32;
	}MD_PITCH_THRESHOLD_HIGH_segments;

}MD_PITCH_THRESHOLD_HIGH_union;

extern union MD_PITCH_THRESHOLD_HIGH_union MD_PITCH_THRESHOLD_HIGH;


/* Frame name: NODE_A::MD_YAW_THRESHOLD_LOW , Frame ID: 26 */


#ifndef MD_YAW_THRESHOLD_LOW_FID 	
#define MD_YAW_THRESHOLD_LOW_FID 	26
#endif

#define MD_YAW_THRESHOLD_LOW_MD_YAW_THRESHOLD_LOW_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_YAW_THRESHOLD_LOW_MD_YAW_THRESHOLD_LOW_START_BIT 	0
#define MD_YAW_THRESHOLD_LOW_MD_YAW_THRESHOLD_LOW_BIT_LENGTH 	32
#define MD_YAW_THRESHOLD_LOW_MD_YAW_THRESHOLD_LOW_FACTOR 	1.0f
#define MD_YAW_THRESHOLD_LOW_MD_YAW_THRESHOLD_LOW_OFFSET 	0.0f
#define MD_YAW_THRESHOLD_LOW_MD_YAW_THRESHOLD_LOW_MINIMUM 	-180.0f
#define MD_YAW_THRESHOLD_LOW_MD_YAW_THRESHOLD_LOW_MAXIMUM 	180.0f



union MD_YAW_THRESHOLD_LOW_union
{
	uint32_t all;

	struct MD_YAW_THRESHOLD_LOW_segments
	{
		 uint32_t MD_YAW_THRESHOLD_LOW:32;
	}MD_YAW_THRESHOLD_LOW_segments;

}MD_YAW_THRESHOLD_LOW_union;

extern union MD_YAW_THRESHOLD_LOW_union MD_YAW_THRESHOLD_LOW;


/* Frame name: NODE_A::MD_YAW_THRESHOLD_HIGH , Frame ID: 27 */


#ifndef MD_YAW_THRESHOLD_HIGH_FID 	
#define MD_YAW_THRESHOLD_HIGH_FID 	27
#endif

#define MD_YAW_THRESHOLD_HIGH_MD_YAW_THRESHOLD_HIGH_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MD_YAW_THRESHOLD_HIGH_MD_YAW_THRESHOLD_HIGH_START_BIT 	0
#define MD_YAW_THRESHOLD_HIGH_MD_YAW_THRESHOLD_HIGH_BIT_LENGTH 	32
#define MD_YAW_THRESHOLD_HIGH_MD_YAW_THRESHOLD_HIGH_FACTOR 	1.0f
#define MD_YAW_THRESHOLD_HIGH_MD_YAW_THRESHOLD_HIGH_OFFSET 	0.0f
#define MD_YAW_THRESHOLD_HIGH_MD_YAW_THRESHOLD_HIGH_MINIMUM 	-180.0f
#define MD_YAW_THRESHOLD_HIGH_MD_YAW_THRESHOLD_HIGH_MAXIMUM 	180.0f



union MD_YAW_THRESHOLD_HIGH_union
{
	uint32_t all;

	struct MD_YAW_THRESHOLD_HIGH_segments
	{
		 uint32_t MD_YAW_THRESHOLD_HIGH:32;
	}MD_YAW_THRESHOLD_HIGH_segments;

}MD_YAW_THRESHOLD_HIGH_union;

extern union MD_YAW_THRESHOLD_HIGH_union MD_YAW_THRESHOLD_HIGH;


/* Frame name: NODE_A::MP_ROLL_FILTER_CONSTANT , Frame ID: 28 */


#ifndef MP_ROLL_FILTER_CONSTANT_FID 	
#define MP_ROLL_FILTER_CONSTANT_FID 	28
#endif

#define MP_ROLL_FILTER_CONSTANT_MP_ROLL_FILTER_CONSTANT_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MP_ROLL_FILTER_CONSTANT_MP_ROLL_FILTER_CONSTANT_START_BIT 	0
#define MP_ROLL_FILTER_CONSTANT_MP_ROLL_FILTER_CONSTANT_BIT_LENGTH 	32
#define MP_ROLL_FILTER_CONSTANT_MP_ROLL_FILTER_CONSTANT_FACTOR 	1.0f
#define MP_ROLL_FILTER_CONSTANT_MP_ROLL_FILTER_CONSTANT_OFFSET 	0.0f
#define MP_ROLL_FILTER_CONSTANT_MP_ROLL_FILTER_CONSTANT_MINIMUM 	0.0f
#define MP_ROLL_FILTER_CONSTANT_MP_ROLL_FILTER_CONSTANT_MAXIMUM 	1.0f



union MP_ROLL_FILTER_CONSTANT_union
{
	uint32_t all;

	struct MP_ROLL_FILTER_CONSTANT_segments
	{
		 uint32_t MP_ROLL_FILTER_CONSTANT:32;
	}MP_ROLL_FILTER_CONSTANT_segments;

}MP_ROLL_FILTER_CONSTANT_union;

extern union MP_ROLL_FILTER_CONSTANT_union MP_ROLL_FILTER_CONSTANT;


/* Frame name: NODE_A::MP_PITCH_FILTER_CONSTANT , Frame ID: 29 */


#ifndef MP_PITCH_FILTER_CONSTANT_FID 	
#define MP_PITCH_FILTER_CONSTANT_FID 	29
#endif

#define MP_PITCH_FILTER_CONSTANT_MP_PITCH_FILTER_CONSTANT_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MP_PITCH_FILTER_CONSTANT_MP_PITCH_FILTER_CONSTANT_START_BIT 	0
#define MP_PITCH_FILTER_CONSTANT_MP_PITCH_FILTER_CONSTANT_BIT_LENGTH 	32
#define MP_PITCH_FILTER_CONSTANT_MP_PITCH_FILTER_CONSTANT_FACTOR 	1.0f
#define MP_PITCH_FILTER_CONSTANT_MP_PITCH_FILTER_CONSTANT_OFFSET 	0.0f
#define MP_PITCH_FILTER_CONSTANT_MP_PITCH_FILTER_CONSTANT_MINIMUM 	0.0f
#define MP_PITCH_FILTER_CONSTANT_MP_PITCH_FILTER_CONSTANT_MAXIMUM 	1.0f



union MP_PITCH_FILTER_CONSTANT_union
{
	uint32_t all;

	struct MP_PITCH_FILTER_CONSTANT_segments
	{
		 uint32_t MP_PITCH_FILTER_CONSTANT:32;
	}MP_PITCH_FILTER_CONSTANT_segments;

}MP_PITCH_FILTER_CONSTANT_union;

extern union MP_PITCH_FILTER_CONSTANT_union MP_PITCH_FILTER_CONSTANT;


/* Frame name: NODE_A::MP_YAW_FILTER_CONSTANT , Frame ID: 30 */


#ifndef MP_YAW_FILTER_CONSTANT_FID 	
#define MP_YAW_FILTER_CONSTANT_FID 	30
#endif

#define MP_YAW_FILTER_CONSTANT_MP_YAW_FILTER_CONSTANT_TYPE 	ADCP_PARAMETER_TYPE_FLOAT32
#define MP_YAW_FILTER_CONSTANT_MP_YAW_FILTER_CONSTANT_START_BIT 	0
#define MP_YAW_FILTER_CONSTANT_MP_YAW_FILTER_CONSTANT_BIT_LENGTH 	32
#define MP_YAW_FILTER_CONSTANT_MP_YAW_FILTER_CONSTANT_FACTOR 	1.0f
#define MP_YAW_FILTER_CONSTANT_MP_YAW_FILTER_CONSTANT_OFFSET 	0.0f
#define MP_YAW_FILTER_CONSTANT_MP_YAW_FILTER_CONSTANT_MINIMUM 	0.0f
#define MP_YAW_FILTER_CONSTANT_MP_YAW_FILTER_CONSTANT_MAXIMUM 	1.0f



union MP_YAW_FILTER_CONSTANT_union
{
	uint32_t all;

	struct MP_YAW_FILTER_CONSTANT_segments
	{
		 uint32_t MP_YAW_FILTER_CONSTANT:32;
	}MP_YAW_FILTER_CONSTANT_segments;

}MP_YAW_FILTER_CONSTANT_union;

extern union MP_YAW_FILTER_CONSTANT_union MP_YAW_FILTER_CONSTANT;


/* Frame name: NODE_A::MP_ROLL_ACCEL , Frame ID: 31 */


#ifndef MP_ROLL_ACCEL_FID 	
#define MP_ROLL_ACCEL_FID 	31
#endif

#define MP_ROLL_ACCEL_MP_ROLL_ACCEL_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_ROLL_ACCEL_MP_ROLL_ACCEL_START_BIT 	0
#define MP_ROLL_ACCEL_MP_ROLL_ACCEL_BIT_LENGTH 	32
#define MP_ROLL_ACCEL_MP_ROLL_ACCEL_FACTOR 	0.001f
#define MP_ROLL_ACCEL_MP_ROLL_ACCEL_OFFSET 	0.0f
#define MP_ROLL_ACCEL_MP_ROLL_ACCEL_MINIMUM 	-180.0f
#define MP_ROLL_ACCEL_MP_ROLL_ACCEL_MAXIMUM 	180.0f



union MP_ROLL_ACCEL_union
{
	uint32_t all;

	struct MP_ROLL_ACCEL_segments
	{
		 uint32_t MP_ROLL_ACCEL:32;
	}MP_ROLL_ACCEL_segments;

}MP_ROLL_ACCEL_union;

extern union MP_ROLL_ACCEL_union MP_ROLL_ACCEL;


/* Frame name: NODE_A::MP_ROLL_GYRO , Frame ID: 32 */


#ifndef MP_ROLL_GYRO_FID 	
#define MP_ROLL_GYRO_FID 	32
#endif

#define MP_ROLL_GYRO_MP_ROLL_GYRO_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_ROLL_GYRO_MP_ROLL_GYRO_START_BIT 	0
#define MP_ROLL_GYRO_MP_ROLL_GYRO_BIT_LENGTH 	32
#define MP_ROLL_GYRO_MP_ROLL_GYRO_FACTOR 	0.001f
#define MP_ROLL_GYRO_MP_ROLL_GYRO_OFFSET 	0.0f
#define MP_ROLL_GYRO_MP_ROLL_GYRO_MINIMUM 	-180.0f
#define MP_ROLL_GYRO_MP_ROLL_GYRO_MAXIMUM 	180.0f



union MP_ROLL_GYRO_union
{
	uint32_t all;

	struct MP_ROLL_GYRO_segments
	{
		 uint32_t MP_ROLL_GYRO:32;
	}MP_ROLL_GYRO_segments;

}MP_ROLL_GYRO_union;

extern union MP_ROLL_GYRO_union MP_ROLL_GYRO;


/* Frame name: NODE_A::MP_ROLL_FILTER , Frame ID: 33 */


#ifndef MP_ROLL_FILTER_FID 	
#define MP_ROLL_FILTER_FID 	33
#endif

#define MP_ROLL_FILTER_MP_ROLL_FILTER_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_ROLL_FILTER_MP_ROLL_FILTER_START_BIT 	0
#define MP_ROLL_FILTER_MP_ROLL_FILTER_BIT_LENGTH 	32
#define MP_ROLL_FILTER_MP_ROLL_FILTER_FACTOR 	0.001f
#define MP_ROLL_FILTER_MP_ROLL_FILTER_OFFSET 	0.0f
#define MP_ROLL_FILTER_MP_ROLL_FILTER_MINIMUM 	-180.0f
#define MP_ROLL_FILTER_MP_ROLL_FILTER_MAXIMUM 	180.0f



union MP_ROLL_FILTER_union
{
	uint32_t all;

	struct MP_ROLL_FILTER_segments
	{
		 uint32_t MP_ROLL_FILTER:32;
	}MP_ROLL_FILTER_segments;

}MP_ROLL_FILTER_union;

extern union MP_ROLL_FILTER_union MP_ROLL_FILTER;


/* Frame name: NODE_A::MP_PITCH_ACCEL , Frame ID: 34 */


#ifndef MP_PITCH_ACCEL_FID 	
#define MP_PITCH_ACCEL_FID 	34
#endif

#define MP_PITCH_ACCEL_MP_PITCH_ACCEL_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_PITCH_ACCEL_MP_PITCH_ACCEL_START_BIT 	0
#define MP_PITCH_ACCEL_MP_PITCH_ACCEL_BIT_LENGTH 	32
#define MP_PITCH_ACCEL_MP_PITCH_ACCEL_FACTOR 	0.001f
#define MP_PITCH_ACCEL_MP_PITCH_ACCEL_OFFSET 	0.0f
#define MP_PITCH_ACCEL_MP_PITCH_ACCEL_MINIMUM 	-180.0f
#define MP_PITCH_ACCEL_MP_PITCH_ACCEL_MAXIMUM 	180.0f



union MP_PITCH_ACCEL_union
{
	uint32_t all;

	struct MP_PITCH_ACCEL_segments
	{
		 uint32_t MP_PITCH_ACCEL:32;
	}MP_PITCH_ACCEL_segments;

}MP_PITCH_ACCEL_union;

extern union MP_PITCH_ACCEL_union MP_PITCH_ACCEL;


/* Frame name: NODE_A::MP_PITCH_GYRO , Frame ID: 35 */


#ifndef MP_PITCH_GYRO_FID 	
#define MP_PITCH_GYRO_FID 	35
#endif

#define MP_PITCH_GYRO_MP_PITCH_GYRO_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_PITCH_GYRO_MP_PITCH_GYRO_START_BIT 	0
#define MP_PITCH_GYRO_MP_PITCH_GYRO_BIT_LENGTH 	32
#define MP_PITCH_GYRO_MP_PITCH_GYRO_FACTOR 	0.001f
#define MP_PITCH_GYRO_MP_PITCH_GYRO_OFFSET 	0.0f
#define MP_PITCH_GYRO_MP_PITCH_GYRO_MINIMUM 	-180.0f
#define MP_PITCH_GYRO_MP_PITCH_GYRO_MAXIMUM 	180.0f



union MP_PITCH_GYRO_union
{
	uint32_t all;

	struct MP_PITCH_GYRO_segments
	{
		 uint32_t MP_PITCH_GYRO:32;
	}MP_PITCH_GYRO_segments;

}MP_PITCH_GYRO_union;

extern union MP_PITCH_GYRO_union MP_PITCH_GYRO;


/* Frame name: NODE_A::MP_PITCH_FILTER , Frame ID: 36 */


#ifndef MP_PITCH_FILTER_FID 	
#define MP_PITCH_FILTER_FID 	36
#endif

#define MP_PITCH_FILTER_MP_PITCH_FILTER_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_PITCH_FILTER_MP_PITCH_FILTER_START_BIT 	0
#define MP_PITCH_FILTER_MP_PITCH_FILTER_BIT_LENGTH 	32
#define MP_PITCH_FILTER_MP_PITCH_FILTER_FACTOR 	0.001f
#define MP_PITCH_FILTER_MP_PITCH_FILTER_OFFSET 	0.0f
#define MP_PITCH_FILTER_MP_PITCH_FILTER_MINIMUM 	-180.0f
#define MP_PITCH_FILTER_MP_PITCH_FILTER_MAXIMUM 	180.0f



union MP_PITCH_FILTER_union
{
	uint32_t all;

	struct MP_PITCH_FILTER_segments
	{
		 uint32_t MP_PITCH_FILTER:32;
	}MP_PITCH_FILTER_segments;

}MP_PITCH_FILTER_union;

extern union MP_PITCH_FILTER_union MP_PITCH_FILTER;


/* Frame name: NODE_A::MP_YAW_ACCEL , Frame ID: 37 */


#ifndef MP_YAW_ACCEL_FID 	
#define MP_YAW_ACCEL_FID 	37
#endif

#define MP_YAW_ACCEL_MP_YAW_ACCEL_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_YAW_ACCEL_MP_YAW_ACCEL_START_BIT 	0
#define MP_YAW_ACCEL_MP_YAW_ACCEL_BIT_LENGTH 	32
#define MP_YAW_ACCEL_MP_YAW_ACCEL_FACTOR 	0.001f
#define MP_YAW_ACCEL_MP_YAW_ACCEL_OFFSET 	0.0f
#define MP_YAW_ACCEL_MP_YAW_ACCEL_MINIMUM 	-180.0f
#define MP_YAW_ACCEL_MP_YAW_ACCEL_MAXIMUM 	180.0f



union MP_YAW_ACCEL_union
{
	uint32_t all;

	struct MP_YAW_ACCEL_segments
	{
		 uint32_t MP_YAW_ACCEL:32;
	}MP_YAW_ACCEL_segments;

}MP_YAW_ACCEL_union;

extern union MP_YAW_ACCEL_union MP_YAW_ACCEL;


/* Frame name: NODE_A::MP_YAW_GYRO , Frame ID: 38 */


#ifndef MP_YAW_GYRO_FID 	
#define MP_YAW_GYRO_FID 	38
#endif

#define MP_YAW_GYRO_MP_YAW_GYRO_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_YAW_GYRO_MP_YAW_GYRO_START_BIT 	0
#define MP_YAW_GYRO_MP_YAW_GYRO_BIT_LENGTH 	32
#define MP_YAW_GYRO_MP_YAW_GYRO_FACTOR 	0.001f
#define MP_YAW_GYRO_MP_YAW_GYRO_OFFSET 	0.0f
#define MP_YAW_GYRO_MP_YAW_GYRO_MINIMUM 	-180.0f
#define MP_YAW_GYRO_MP_YAW_GYRO_MAXIMUM 	180.0f



union MP_YAW_GYRO_union
{
	uint32_t all;

	struct MP_YAW_GYRO_segments
	{
		 uint32_t MP_YAW_GYRO:32;
	}MP_YAW_GYRO_segments;

}MP_YAW_GYRO_union;

extern union MP_YAW_GYRO_union MP_YAW_GYRO;


/* Frame name: NODE_A::MP_YAW_FILTER , Frame ID: 39 */


#ifndef MP_YAW_FILTER_FID 	
#define MP_YAW_FILTER_FID 	39
#endif

#define MP_YAW_FILTER_MP_YAW_FILTER_TYPE 	ADCP_PARAMETER_TYPE_SIGNED
#define MP_YAW_FILTER_MP_YAW_FILTER_START_BIT 	0
#define MP_YAW_FILTER_MP_YAW_FILTER_BIT_LENGTH 	32
#define MP_YAW_FILTER_MP_YAW_FILTER_FACTOR 	0.001f
#define MP_YAW_FILTER_MP_YAW_FILTER_OFFSET 	0.0f
#define MP_YAW_FILTER_MP_YAW_FILTER_MINIMUM 	-180.0f
#define MP_YAW_FILTER_MP_YAW_FILTER_MAXIMUM 	180.0f



union MP_YAW_FILTER_union
{
	uint32_t all;

	struct MP_YAW_FILTER_segments
	{
		 uint32_t MP_YAW_FILTER:32;
	}MP_YAW_FILTER_segments;

}MP_YAW_FILTER_union;

extern union MP_YAW_FILTER_union MP_YAW_FILTER;


/* Frame name: NODE_A::MD_WRITE_CONFIG , Frame ID: 40 */


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_LOW_WE_START_BIT 	0
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_HIGH_WE_START_BIT 	1
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_LOW_WE_START_BIT 	2
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_HIGH_WE_START_BIT 	3
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_LOW_WE_START_BIT 	4
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_HIGH_WE_START_BIT 	5
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_LOW_WE_START_BIT 	6
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_HIGH_WE_START_BIT 	7
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_LOW_WE_START_BIT 	8
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_HIGH_WE_START_BIT 	9
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_LOW_WE_START_BIT 	10
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_HIGH_WE_START_BIT 	11
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_LOW_WE_START_BIT 	12
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_HIGH_WE_START_BIT 	13
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_LOW_WE_START_BIT 	14
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_HIGH_WE_START_BIT 	15
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_LOW_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_LOW_WE_START_BIT 	16
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_LOW_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_LOW_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_LOW_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_LOW_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_LOW_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_HIGH_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_HIGH_WE_START_BIT 	17
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_HIGH_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_HIGH_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_HIGH_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_HIGH_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_HIGH_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MP_ROLL_FILTER_CONSTANT_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MP_ROLL_FILTER_CONSTANT_WE_START_BIT 	18
#define MD_WRITE_CONFIG_MP_ROLL_FILTER_CONSTANT_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MP_ROLL_FILTER_CONSTANT_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MP_ROLL_FILTER_CONSTANT_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MP_ROLL_FILTER_CONSTANT_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MP_ROLL_FILTER_CONSTANT_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MP_PITCH_FILTER_CONSTANT_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MP_PITCH_FILTER_CONSTANT_WE_START_BIT 	19
#define MD_WRITE_CONFIG_MP_PITCH_FILTER_CONSTANT_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MP_PITCH_FILTER_CONSTANT_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MP_PITCH_FILTER_CONSTANT_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MP_PITCH_FILTER_CONSTANT_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MP_PITCH_FILTER_CONSTANT_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MP_YAW_FILTER_CONSTANT_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MP_YAW_FILTER_CONSTANT_WE_START_BIT 	20
#define MD_WRITE_CONFIG_MP_YAW_FILTER_CONSTANT_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MP_YAW_FILTER_CONSTANT_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MP_YAW_FILTER_CONSTANT_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MP_YAW_FILTER_CONSTANT_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MP_YAW_FILTER_CONSTANT_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_TYPE_WE_START_BIT 	21
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_X_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_TYPE_WE_START_BIT 	22
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Y_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_TYPE_WE_START_BIT 	23
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ACCEL_Z_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_TYPE_WE_START_BIT 	24
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_X_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_TYPE_WE_START_BIT 	25
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Y_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_TYPE_WE_START_BIT 	26
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_GYRO_Z_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_TYPE_WE_START_BIT 	27
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_ROLL_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_TYPE_WE_START_BIT 	28
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_PITCH_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f


#ifndef MD_WRITE_CONFIG_FID 	
#define MD_WRITE_CONFIG_FID 	40
#endif

#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_TYPE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_TYPE_WE_START_BIT 	29
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_TYPE_WE_BIT_LENGTH 	1
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_TYPE_WE_FACTOR 	1.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_TYPE_WE_OFFSET 	0.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_TYPE_WE_MINIMUM 	0.0f
#define MD_WRITE_CONFIG_MD_YAW_THRESHOLD_TYPE_WE_MAXIMUM 	1.0f



union MD_WRITE_CONFIG_union
{
	uint32_t all;

	struct MD_WRITE_CONFIG_segments
	{
		 uint32_t MD_ACCEL_X_THRESHOLD_LOW_WE:1;
		 uint32_t MD_ACCEL_X_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_ACCEL_Y_THRESHOLD_LOW_WE:1;
		 uint32_t MD_ACCEL_Y_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_ACCEL_Z_THRESHOLD_LOW_WE:1;
		 uint32_t MD_ACCEL_Z_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_GYRO_X_THRESHOLD_LOW_WE:1;
		 uint32_t MD_GYRO_X_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_GYRO_Y_THRESHOLD_LOW_WE:1;
		 uint32_t MD_GYRO_Y_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_GYRO_Z_THRESHOLD_LOW_WE:1;
		 uint32_t MD_GYRO_Z_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_ROLL_THRESHOLD_LOW_WE:1;
		 uint32_t MD_ROLL_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_PITCH_THRESHOLD_LOW_WE:1;
		 uint32_t MD_PITCH_THRESHOLD_HIGH_WE:1;
		 uint32_t MD_YAW_THRESHOLD_LOW_WE:1;
		 uint32_t MD_YAW_THRESHOLD_HIGH_WE:1;
		 uint32_t MP_ROLL_FILTER_CONSTANT_WE:1;
		 uint32_t MP_PITCH_FILTER_CONSTANT_WE:1;
		 uint32_t MP_YAW_FILTER_CONSTANT_WE:1;
		 uint32_t MD_ACCEL_X_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_ACCEL_Y_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_ACCEL_Z_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_GYRO_X_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_GYRO_Y_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_GYRO_Z_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_ROLL_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_PITCH_THRESHOLD_TYPE_WE:1;
		 uint32_t MD_YAW_THRESHOLD_TYPE_WE:1;
	}MD_WRITE_CONFIG_segments;

}MD_WRITE_CONFIG_union;

extern union MD_WRITE_CONFIG_union MD_WRITE_CONFIG;


/* Frame name: NODE_A::MD_OUTPUT , Frame ID: 41 */


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_ACCEL_X_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_ACCEL_X_START_BIT 	0
#define MD_OUTPUT_MD_OUTPUT_ACCEL_X_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_ACCEL_X_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_X_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_X_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_X_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_ACCEL_Y_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Y_START_BIT 	1
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Y_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Y_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Y_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Y_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Y_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_ACCEL_Z_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Z_START_BIT 	2
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Z_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Z_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Z_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Z_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ACCEL_Z_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_GYRO_X_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_GYRO_X_START_BIT 	3
#define MD_OUTPUT_MD_OUTPUT_GYRO_X_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_GYRO_X_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_X_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_X_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_X_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_GYRO_Y_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_GYRO_Y_START_BIT 	4
#define MD_OUTPUT_MD_OUTPUT_GYRO_Y_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_GYRO_Y_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_Y_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_Y_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_Y_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_GYRO_Z_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_GYRO_Z_START_BIT 	5
#define MD_OUTPUT_MD_OUTPUT_GYRO_Z_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_GYRO_Z_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_Z_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_Z_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_GYRO_Z_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_ROLL_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_ROLL_START_BIT 	6
#define MD_OUTPUT_MD_OUTPUT_ROLL_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_ROLL_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_ROLL_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ROLL_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_ROLL_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_PITCH_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_PITCH_START_BIT 	7
#define MD_OUTPUT_MD_OUTPUT_PITCH_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_PITCH_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_PITCH_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_PITCH_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_PITCH_MAXIMUM 	1.0f


#ifndef MD_OUTPUT_FID 	
#define MD_OUTPUT_FID 	41
#endif

#define MD_OUTPUT_MD_OUTPUT_YAW_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define MD_OUTPUT_MD_OUTPUT_YAW_START_BIT 	8
#define MD_OUTPUT_MD_OUTPUT_YAW_BIT_LENGTH 	1
#define MD_OUTPUT_MD_OUTPUT_YAW_FACTOR 	1.0f
#define MD_OUTPUT_MD_OUTPUT_YAW_OFFSET 	0.0f
#define MD_OUTPUT_MD_OUTPUT_YAW_MINIMUM 	0.0f
#define MD_OUTPUT_MD_OUTPUT_YAW_MAXIMUM 	1.0f



union MD_OUTPUT_union
{
	uint32_t all;

	struct MD_OUTPUT_segments
	{
		 uint32_t MD_OUTPUT_ACCEL_X:1;
		 uint32_t MD_OUTPUT_ACCEL_Y:1;
		 uint32_t MD_OUTPUT_ACCEL_Z:1;
		 uint32_t MD_OUTPUT_GYRO_X:1;
		 uint32_t MD_OUTPUT_GYRO_Y:1;
		 uint32_t MD_OUTPUT_GYRO_Z:1;
		 uint32_t MD_OUTPUT_ROLL:1;
		 uint32_t MD_OUTPUT_PITCH:1;
		 uint32_t MD_OUTPUT_YAW:1;
	}MD_OUTPUT_segments;

}MD_OUTPUT_union;

extern union MD_OUTPUT_union MD_OUTPUT;


/* Frame name: NODE_A::LED_MODE_CONFIG , Frame ID: 42 */


#ifndef LED_MODE_CONFIG_FID 	
#define LED_MODE_CONFIG_FID 	42
#endif

#define LED_MODE_CONFIG_LED1_MODE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_MODE_CONFIG_LED1_MODE_START_BIT 	0
#define LED_MODE_CONFIG_LED1_MODE_BIT_LENGTH 	5
#define LED_MODE_CONFIG_LED1_MODE_FACTOR 	1.0f
#define LED_MODE_CONFIG_LED1_MODE_OFFSET 	0.0f
#define LED_MODE_CONFIG_LED1_MODE_MINIMUM 	0.0f
#define LED_MODE_CONFIG_LED1_MODE_MAXIMUM 	32.0f


#ifndef LED_MODE_CONFIG_FID 	
#define LED_MODE_CONFIG_FID 	42
#endif

#define LED_MODE_CONFIG_LED2_MODE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_MODE_CONFIG_LED2_MODE_START_BIT 	5
#define LED_MODE_CONFIG_LED2_MODE_BIT_LENGTH 	5
#define LED_MODE_CONFIG_LED2_MODE_FACTOR 	1.0f
#define LED_MODE_CONFIG_LED2_MODE_OFFSET 	0.0f
#define LED_MODE_CONFIG_LED2_MODE_MINIMUM 	0.0f
#define LED_MODE_CONFIG_LED2_MODE_MAXIMUM 	32.0f


#ifndef LED_MODE_CONFIG_FID 	
#define LED_MODE_CONFIG_FID 	42
#endif

#define LED_MODE_CONFIG_LED3_MODE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_MODE_CONFIG_LED3_MODE_START_BIT 	10
#define LED_MODE_CONFIG_LED3_MODE_BIT_LENGTH 	5
#define LED_MODE_CONFIG_LED3_MODE_FACTOR 	1.0f
#define LED_MODE_CONFIG_LED3_MODE_OFFSET 	0.0f
#define LED_MODE_CONFIG_LED3_MODE_MINIMUM 	0.0f
#define LED_MODE_CONFIG_LED3_MODE_MAXIMUM 	32.0f


#ifndef LED_MODE_CONFIG_FID 	
#define LED_MODE_CONFIG_FID 	42
#endif

#define LED_MODE_CONFIG_LED1_MODE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_MODE_CONFIG_LED1_MODE_WE_START_BIT 	15
#define LED_MODE_CONFIG_LED1_MODE_WE_BIT_LENGTH 	1
#define LED_MODE_CONFIG_LED1_MODE_WE_FACTOR 	1.0f
#define LED_MODE_CONFIG_LED1_MODE_WE_OFFSET 	0.0f
#define LED_MODE_CONFIG_LED1_MODE_WE_MINIMUM 	0.0f
#define LED_MODE_CONFIG_LED1_MODE_WE_MAXIMUM 	1.0f


#ifndef LED_MODE_CONFIG_FID 	
#define LED_MODE_CONFIG_FID 	42
#endif

#define LED_MODE_CONFIG_LED2_MODE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_MODE_CONFIG_LED2_MODE_WE_START_BIT 	16
#define LED_MODE_CONFIG_LED2_MODE_WE_BIT_LENGTH 	1
#define LED_MODE_CONFIG_LED2_MODE_WE_FACTOR 	1.0f
#define LED_MODE_CONFIG_LED2_MODE_WE_OFFSET 	0.0f
#define LED_MODE_CONFIG_LED2_MODE_WE_MINIMUM 	0.0f
#define LED_MODE_CONFIG_LED2_MODE_WE_MAXIMUM 	1.0f


#ifndef LED_MODE_CONFIG_FID 	
#define LED_MODE_CONFIG_FID 	42
#endif

#define LED_MODE_CONFIG_LED3_MODE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_MODE_CONFIG_LED3_MODE_WE_START_BIT 	17
#define LED_MODE_CONFIG_LED3_MODE_WE_BIT_LENGTH 	1
#define LED_MODE_CONFIG_LED3_MODE_WE_FACTOR 	1.0f
#define LED_MODE_CONFIG_LED3_MODE_WE_OFFSET 	0.0f
#define LED_MODE_CONFIG_LED3_MODE_WE_MINIMUM 	0.0f
#define LED_MODE_CONFIG_LED3_MODE_WE_MAXIMUM 	1.0f



union LED_MODE_CONFIG_union
{
	uint32_t all;

	struct LED_MODE_CONFIG_segments
	{
		 uint32_t LED1_MODE:5;
		 uint32_t LED2_MODE:5;
		 uint32_t LED3_MODE:5;
		 uint32_t LED1_MODE_WE:1;
		 uint32_t LED2_MODE_WE:1;
		 uint32_t LED3_MODE_WE:1;
	}LED_MODE_CONFIG_segments;

}LED_MODE_CONFIG_union;

extern union LED_MODE_CONFIG_union LED_MODE_CONFIG;


/* Frame name: NODE_A::LED_UC_WRITE , Frame ID: 42 */


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED1_UC_STATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED1_UC_STATE_START_BIT 	0
#define LED_UC_WRITE_LED1_UC_STATE_BIT_LENGTH 	1
#define LED_UC_WRITE_LED1_UC_STATE_FACTOR 	1.0f
#define LED_UC_WRITE_LED1_UC_STATE_OFFSET 	0.0f
#define LED_UC_WRITE_LED1_UC_STATE_MINIMUM 	0.0f
#define LED_UC_WRITE_LED1_UC_STATE_MAXIMUM 	1.0f


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED2_UC_STATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED2_UC_STATE_START_BIT 	1
#define LED_UC_WRITE_LED2_UC_STATE_BIT_LENGTH 	1
#define LED_UC_WRITE_LED2_UC_STATE_FACTOR 	1.0f
#define LED_UC_WRITE_LED2_UC_STATE_OFFSET 	0.0f
#define LED_UC_WRITE_LED2_UC_STATE_MINIMUM 	0.0f
#define LED_UC_WRITE_LED2_UC_STATE_MAXIMUM 	1.0f


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED3_UC_STATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED3_UC_STATE_START_BIT 	2
#define LED_UC_WRITE_LED3_UC_STATE_BIT_LENGTH 	1
#define LED_UC_WRITE_LED3_UC_STATE_FACTOR 	1.0f
#define LED_UC_WRITE_LED3_UC_STATE_OFFSET 	0.0f
#define LED_UC_WRITE_LED3_UC_STATE_MINIMUM 	0.0f
#define LED_UC_WRITE_LED3_UC_STATE_MAXIMUM 	1.0f


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED1_UC_DUTY_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED1_UC_DUTY_START_BIT 	3
#define LED_UC_WRITE_LED1_UC_DUTY_BIT_LENGTH 	8
#define LED_UC_WRITE_LED1_UC_DUTY_FACTOR 	1.0f
#define LED_UC_WRITE_LED1_UC_DUTY_OFFSET 	0.0f
#define LED_UC_WRITE_LED1_UC_DUTY_MINIMUM 	0.0f
#define LED_UC_WRITE_LED1_UC_DUTY_MAXIMUM 	100.0f


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED2_UC_DUTY_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED2_UC_DUTY_START_BIT 	11
#define LED_UC_WRITE_LED2_UC_DUTY_BIT_LENGTH 	8
#define LED_UC_WRITE_LED2_UC_DUTY_FACTOR 	1.0f
#define LED_UC_WRITE_LED2_UC_DUTY_OFFSET 	0.0f
#define LED_UC_WRITE_LED2_UC_DUTY_MINIMUM 	0.0f
#define LED_UC_WRITE_LED2_UC_DUTY_MAXIMUM 	100.0f


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED3_UC_DUTY_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED3_UC_DUTY_START_BIT 	19
#define LED_UC_WRITE_LED3_UC_DUTY_BIT_LENGTH 	8
#define LED_UC_WRITE_LED3_UC_DUTY_FACTOR 	1.0f
#define LED_UC_WRITE_LED3_UC_DUTY_OFFSET 	0.0f
#define LED_UC_WRITE_LED3_UC_DUTY_MINIMUM 	0.0f
#define LED_UC_WRITE_LED3_UC_DUTY_MAXIMUM 	100.0f


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED_UC_STATE_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED_UC_STATE_WE_START_BIT 	27
#define LED_UC_WRITE_LED_UC_STATE_WE_BIT_LENGTH 	1
#define LED_UC_WRITE_LED_UC_STATE_WE_FACTOR 	1.0f
#define LED_UC_WRITE_LED_UC_STATE_WE_OFFSET 	0.0f
#define LED_UC_WRITE_LED_UC_STATE_WE_MINIMUM 	0.0f
#define LED_UC_WRITE_LED_UC_STATE_WE_MAXIMUM 	1.0f


#ifndef LED_UC_WRITE_FID 	
#define LED_UC_WRITE_FID 	42
#endif

#define LED_UC_WRITE_LED_UC_DUTY_WE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_UC_WRITE_LED_UC_DUTY_WE_START_BIT 	28
#define LED_UC_WRITE_LED_UC_DUTY_WE_BIT_LENGTH 	1
#define LED_UC_WRITE_LED_UC_DUTY_WE_FACTOR 	1.0f
#define LED_UC_WRITE_LED_UC_DUTY_WE_OFFSET 	0.0f
#define LED_UC_WRITE_LED_UC_DUTY_WE_MINIMUM 	0.0f
#define LED_UC_WRITE_LED_UC_DUTY_WE_MAXIMUM 	1.0f



union LED_UC_WRITE_union
{
	uint32_t all;

	struct LED_UC_WRITE_segments
	{
		 uint32_t LED1_UC_STATE:1;
		 uint32_t LED2_UC_STATE:1;
		 uint32_t LED3_UC_STATE:1;
		 uint32_t LED1_UC_DUTY:8;
		 uint32_t LED2_UC_DUTY:8;
		 uint32_t LED3_UC_DUTY:8;
		 uint32_t LED_UC_STATE_WE:1;
		 uint32_t LED_UC_DUTY_WE:1;
	}LED_UC_WRITE_segments;

}LED_UC_WRITE_union;

extern union LED_UC_WRITE_union LED_UC_WRITE;


/* Frame name: NODE_A::LED_OUTPUT , Frame ID: 43 */


#ifndef LED_OUTPUT_FID 	
#define LED_OUTPUT_FID 	43
#endif

#define LED_OUTPUT_LED1_OUTPUT_STATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_OUTPUT_LED1_OUTPUT_STATE_START_BIT 	0
#define LED_OUTPUT_LED1_OUTPUT_STATE_BIT_LENGTH 	1
#define LED_OUTPUT_LED1_OUTPUT_STATE_FACTOR 	1.0f
#define LED_OUTPUT_LED1_OUTPUT_STATE_OFFSET 	0.0f
#define LED_OUTPUT_LED1_OUTPUT_STATE_MINIMUM 	0.0f
#define LED_OUTPUT_LED1_OUTPUT_STATE_MAXIMUM 	1.0f


#ifndef LED_OUTPUT_FID 	
#define LED_OUTPUT_FID 	43
#endif

#define LED_OUTPUT_LED2_OUTPUT_STATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_OUTPUT_LED2_OUTPUT_STATE_START_BIT 	1
#define LED_OUTPUT_LED2_OUTPUT_STATE_BIT_LENGTH 	1
#define LED_OUTPUT_LED2_OUTPUT_STATE_FACTOR 	1.0f
#define LED_OUTPUT_LED2_OUTPUT_STATE_OFFSET 	0.0f
#define LED_OUTPUT_LED2_OUTPUT_STATE_MINIMUM 	0.0f
#define LED_OUTPUT_LED2_OUTPUT_STATE_MAXIMUM 	1.0f


#ifndef LED_OUTPUT_FID 	
#define LED_OUTPUT_FID 	43
#endif

#define LED_OUTPUT_LED3_OUTPUT_STATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_OUTPUT_LED3_OUTPUT_STATE_START_BIT 	2
#define LED_OUTPUT_LED3_OUTPUT_STATE_BIT_LENGTH 	1
#define LED_OUTPUT_LED3_OUTPUT_STATE_FACTOR 	1.0f
#define LED_OUTPUT_LED3_OUTPUT_STATE_OFFSET 	0.0f
#define LED_OUTPUT_LED3_OUTPUT_STATE_MINIMUM 	0.0f
#define LED_OUTPUT_LED3_OUTPUT_STATE_MAXIMUM 	1.0f


#ifndef LED_OUTPUT_FID 	
#define LED_OUTPUT_FID 	43
#endif

#define LED_OUTPUT_LED1_OUTPUT_DUTY_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_OUTPUT_LED1_OUTPUT_DUTY_START_BIT 	3
#define LED_OUTPUT_LED1_OUTPUT_DUTY_BIT_LENGTH 	8
#define LED_OUTPUT_LED1_OUTPUT_DUTY_FACTOR 	1.0f
#define LED_OUTPUT_LED1_OUTPUT_DUTY_OFFSET 	0.0f
#define LED_OUTPUT_LED1_OUTPUT_DUTY_MINIMUM 	0.0f
#define LED_OUTPUT_LED1_OUTPUT_DUTY_MAXIMUM 	100.0f


#ifndef LED_OUTPUT_FID 	
#define LED_OUTPUT_FID 	43
#endif

#define LED_OUTPUT_LED2_OUTPUT_DUTY_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_OUTPUT_LED2_OUTPUT_DUTY_START_BIT 	11
#define LED_OUTPUT_LED2_OUTPUT_DUTY_BIT_LENGTH 	8
#define LED_OUTPUT_LED2_OUTPUT_DUTY_FACTOR 	1.0f
#define LED_OUTPUT_LED2_OUTPUT_DUTY_OFFSET 	0.0f
#define LED_OUTPUT_LED2_OUTPUT_DUTY_MINIMUM 	0.0f
#define LED_OUTPUT_LED2_OUTPUT_DUTY_MAXIMUM 	100.0f


#ifndef LED_OUTPUT_FID 	
#define LED_OUTPUT_FID 	43
#endif

#define LED_OUTPUT_LED3_OUTPUT_DUTY_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define LED_OUTPUT_LED3_OUTPUT_DUTY_START_BIT 	19
#define LED_OUTPUT_LED3_OUTPUT_DUTY_BIT_LENGTH 	8
#define LED_OUTPUT_LED3_OUTPUT_DUTY_FACTOR 	1.0f
#define LED_OUTPUT_LED3_OUTPUT_DUTY_OFFSET 	0.0f
#define LED_OUTPUT_LED3_OUTPUT_DUTY_MINIMUM 	0.0f
#define LED_OUTPUT_LED3_OUTPUT_DUTY_MAXIMUM 	100.0f



union LED_OUTPUT_union
{
	uint32_t all;

	struct LED_OUTPUT_segments
	{
		 uint32_t LED1_OUTPUT_STATE:1;
		 uint32_t LED2_OUTPUT_STATE:1;
		 uint32_t LED3_OUTPUT_STATE:1;
		 uint32_t LED1_OUTPUT_DUTY:8;
		 uint32_t LED2_OUTPUT_DUTY:8;
		 uint32_t LED3_OUTPUT_DUTY:8;
	}LED_OUTPUT_segments;

}LED_OUTPUT_union;

extern union LED_OUTPUT_union LED_OUTPUT;


/* Frame name: NODE_A::CONTROL , Frame ID: 44 */


#ifndef CONTROL_FID 	
#define CONTROL_FID 	44
#endif

#define CONTROL_CONFIG_SAVE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define CONTROL_CONFIG_SAVE_START_BIT 	0
#define CONTROL_CONFIG_SAVE_BIT_LENGTH 	1
#define CONTROL_CONFIG_SAVE_FACTOR 	1.0f
#define CONTROL_CONFIG_SAVE_OFFSET 	0.0f
#define CONTROL_CONFIG_SAVE_MINIMUM 	0.0f
#define CONTROL_CONFIG_SAVE_MAXIMUM 	1.0f


#ifndef CONTROL_FID 	
#define CONTROL_FID 	44
#endif

#define CONTROL_IMU_CALIBRATE_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define CONTROL_IMU_CALIBRATE_START_BIT 	1
#define CONTROL_IMU_CALIBRATE_BIT_LENGTH 	1
#define CONTROL_IMU_CALIBRATE_FACTOR 	1.0f
#define CONTROL_IMU_CALIBRATE_OFFSET 	0.0f
#define CONTROL_IMU_CALIBRATE_MINIMUM 	0.0f
#define CONTROL_IMU_CALIBRATE_MAXIMUM 	1.0f


#ifndef CONTROL_FID 	
#define CONTROL_FID 	44
#endif

#define CONTROL_MP_RESET_TYPE 	ADCP_PARAMETER_TYPE_UNSIGNED
#define CONTROL_MP_RESET_START_BIT 	2
#define CONTROL_MP_RESET_BIT_LENGTH 	1
#define CONTROL_MP_RESET_FACTOR 	1.0f
#define CONTROL_MP_RESET_OFFSET 	0.0f
#define CONTROL_MP_RESET_MINIMUM 	0.0f
#define CONTROL_MP_RESET_MAXIMUM 	1.0f



union CONTROL_union
{
	uint32_t all;

	struct CONTROL_segments
	{
		 uint32_t CONFIG_SAVE:1;
		 uint32_t IMU_CALIBRATE:1;
		 uint32_t MP_RESET:1;
	}CONTROL_segments;

}CONTROL_union;

extern union CONTROL_union CONTROL;

#endif /* ADCP_FRAMES_H */
