
#ifndef ADCP_RECEIVE_H_
#define ADCP_RECEIVE_H_

#include "ADCP.h"
#include "ADCP_frames.h"
#include "system.h"


/*   MPU Stick Writable Parameter Indices    */

#define WRITE_PARAMETER_INDEX__IMU_CONFIG_SAMPLING_RATE    (uint8_t)0
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_CALIB_INTERVAL    (uint8_t)1
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_CALIB_POINTS    (uint8_t)2
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_GYRO_BW    (uint8_t)3
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_ACCEL_BW    (uint8_t)4
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_GYRO_FS    (uint8_t)5
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_ACCEL_FS    (uint8_t)6
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_SAMPLING_RATE_WE    (uint8_t)7
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_CALIB_INTERVAL_WE    (uint8_t)8
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_CALIB_POINTS_WE    (uint8_t)9
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_GYRO_BW_WE    (uint8_t)10
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_ACCEL_BW_WE    (uint8_t)11
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_GYRO_FS_WE    (uint8_t)12
#define WRITE_PARAMETER_INDEX__IMU_CONFIG_ACCEL_FS_WE    (uint8_t)13
#define WRITE_PARAMETER_INDEX__MD_ACCEL_X_THRESHOLD_TYPE    (uint8_t)14
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Y_THRESHOLD_TYPE    (uint8_t)15
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Z_THRESHOLD_TYPE    (uint8_t)16
#define WRITE_PARAMETER_INDEX__MD_GYRO_X_THRESHOLD_TYPE    (uint8_t)17
#define WRITE_PARAMETER_INDEX__MD_GYRO_Y_THRESHOLD_TYPE    (uint8_t)18
#define WRITE_PARAMETER_INDEX__MD_GYRO_Z_THRESHOLD_TYPE    (uint8_t)19
#define WRITE_PARAMETER_INDEX__MD_ROLL_THRESHOLD_TYPE    (uint8_t)20
#define WRITE_PARAMETER_INDEX__MD_PITCH_THRESHOLD_TYPE    (uint8_t)21
#define WRITE_PARAMETER_INDEX__MD_YAW_THRESHOLD_TYPE    (uint8_t)22
#define WRITE_PARAMETER_INDEX__MD_ACCEL_X_THRESHOLD_LOW    (uint8_t)23
#define WRITE_PARAMETER_INDEX__MD_ACCEL_X_THRESHOLD_HIGH    (uint8_t)24
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Y_THRESHOLD_LOW    (uint8_t)25
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Y_THRESHOLD_HIGH    (uint8_t)26
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Z_THRESHOLD_LOW    (uint8_t)27
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Z_THRESHOLD_HIGH    (uint8_t)28
#define WRITE_PARAMETER_INDEX__MD_GYRO_X_THRESHOLD_LOW    (uint8_t)29
#define WRITE_PARAMETER_INDEX__MD_GYRO_X_THRESHOLD_HIGH    (uint8_t)30
#define WRITE_PARAMETER_INDEX__MD_GYRO_Y_THRESHOLD_LOW    (uint8_t)31
#define WRITE_PARAMETER_INDEX__MD_GYRO_Y_THRESHOLD_HIGH    (uint8_t)32
#define WRITE_PARAMETER_INDEX__MD_GYRO_Z_THRESHOLD_LOW    (uint8_t)33
#define WRITE_PARAMETER_INDEX__MD_GYRO_Z_THRESHOLD_HIGH    (uint8_t)34
#define WRITE_PARAMETER_INDEX__MD_ROLL_THRESHOLD_LOW    (uint8_t)35
#define WRITE_PARAMETER_INDEX__MD_ROLL_THRESHOLD_HIGH    (uint8_t)36
#define WRITE_PARAMETER_INDEX__MD_PITCH_THRESHOLD_LOW    (uint8_t)37
#define WRITE_PARAMETER_INDEX__MD_PITCH_THRESHOLD_HIGH    (uint8_t)38
#define WRITE_PARAMETER_INDEX__MD_YAW_THRESHOLD_LOW    (uint8_t)39
#define WRITE_PARAMETER_INDEX__MD_YAW_THRESHOLD_HIGH    (uint8_t)40
#define WRITE_PARAMETER_INDEX__MP_ROLL_FILTER_CONSTANT    (uint8_t)41
#define WRITE_PARAMETER_INDEX__MP_PITCH_FILTER_CONSTANT    (uint8_t)42
#define WRITE_PARAMETER_INDEX__MP_YAW_FILTER_CONSTANT    (uint8_t)43
#define WRITE_PARAMETER_INDEX__MD_ACCEL_X_THRESHOLD_LOW_WE    (uint8_t)44
#define WRITE_PARAMETER_INDEX__MD_ACCEL_X_THRESHOLD_HIGH_WE    (uint8_t)45
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Y_THRESHOLD_LOW_WE    (uint8_t)46
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Y_THRESHOLD_HIGH_WE    (uint8_t)47
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Z_THRESHOLD_LOW_WE    (uint8_t)48
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Z_THRESHOLD_HIGH_WE    (uint8_t)49
#define WRITE_PARAMETER_INDEX__MD_GYRO_X_THRESHOLD_LOW_WE    (uint8_t)50
#define WRITE_PARAMETER_INDEX__MD_GYRO_X_THRESHOLD_HIGH_WE    (uint8_t)51
#define WRITE_PARAMETER_INDEX__MD_GYRO_Y_THRESHOLD_LOW_WE    (uint8_t)52
#define WRITE_PARAMETER_INDEX__MD_GYRO_Y_THRESHOLD_HIGH_WE    (uint8_t)53
#define WRITE_PARAMETER_INDEX__MD_GYRO_Z_THRESHOLD_LOW_WE    (uint8_t)54
#define WRITE_PARAMETER_INDEX__MD_GYRO_Z_THRESHOLD_HIGH_WE    (uint8_t)55
#define WRITE_PARAMETER_INDEX__MD_ROLL_THRESHOLD_LOW_WE    (uint8_t)56
#define WRITE_PARAMETER_INDEX__MD_ROLL_THRESHOLD_HIGH_WE    (uint8_t)57
#define WRITE_PARAMETER_INDEX__MD_PITCH_THRESHOLD_LOW_WE    (uint8_t)58
#define WRITE_PARAMETER_INDEX__MD_PITCH_THRESHOLD_HIGH_WE    (uint8_t)59
#define WRITE_PARAMETER_INDEX__MD_YAW_THRESHOLD_LOW_WE    (uint8_t)60
#define WRITE_PARAMETER_INDEX__MD_YAW_THRESHOLD_HIGH_WE    (uint8_t)61
#define WRITE_PARAMETER_INDEX__MP_ROLL_FILTER_CONSTANT_WE    (uint8_t)62
#define WRITE_PARAMETER_INDEX__MP_PITCH_FILTER_CONSTANT_WE    (uint8_t)63
#define WRITE_PARAMETER_INDEX__MP_YAW_FILTER_CONSTANT_WE    (uint8_t)64
#define WRITE_PARAMETER_INDEX__MD_ACCEL_X_THRESHOLD_TYPE_WE    (uint8_t)65
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Y_THRESHOLD_TYPE_WE    (uint8_t)66
#define WRITE_PARAMETER_INDEX__MD_ACCEL_Z_THRESHOLD_TYPE_WE    (uint8_t)67
#define WRITE_PARAMETER_INDEX__MD_GYRO_X_THRESHOLD_TYPE_WE    (uint8_t)68
#define WRITE_PARAMETER_INDEX__MD_GYRO_Y_THRESHOLD_TYPE_WE    (uint8_t)69
#define WRITE_PARAMETER_INDEX__MD_GYRO_Z_THRESHOLD_TYPE_WE    (uint8_t)70
#define WRITE_PARAMETER_INDEX__MD_ROLL_THRESHOLD_TYPE_WE    (uint8_t)71
#define WRITE_PARAMETER_INDEX__MD_PITCH_THRESHOLD_TYPE_WE    (uint8_t)72
#define WRITE_PARAMETER_INDEX__MD_YAW_THRESHOLD_TYPE_WE    (uint8_t)73
#define WRITE_PARAMETER_INDEX__LED1_MODE    (uint8_t)74
#define WRITE_PARAMETER_INDEX__LED2_MODE    (uint8_t)75
#define WRITE_PARAMETER_INDEX__LED3_MODE    (uint8_t)76
#define WRITE_PARAMETER_INDEX__LED1_MODE_WE    (uint8_t)77
#define WRITE_PARAMETER_INDEX__LED2_MODE_WE    (uint8_t)78
#define WRITE_PARAMETER_INDEX__LED3_MODE_WE    (uint8_t)79
#define WRITE_PARAMETER_INDEX__LED1_UC_STATE    (uint8_t)80
#define WRITE_PARAMETER_INDEX__LED2_UC_STATE    (uint8_t)81
#define WRITE_PARAMETER_INDEX__LED3_UC_STATE    (uint8_t)82
#define WRITE_PARAMETER_INDEX__LED1_UC_DUTY    (uint8_t)83
#define WRITE_PARAMETER_INDEX__LED2_UC_DUTY    (uint8_t)84
#define WRITE_PARAMETER_INDEX__LED3_UC_DUTY    (uint8_t)85
#define WRITE_PARAMETER_INDEX__LED_UC_STATE_WE    (uint8_t)86
#define WRITE_PARAMETER_INDEX__LED_UC_DUTY_WE    (uint8_t)87
#define WRITE_PARAMETER_INDEX__CONFIG_SAVE    (uint8_t)88
#define WRITE_PARAMETER_INDEX__IMU_CALIBRATE    (uint8_t)89
#define WRITE_PARAMETER_INDEX__MP_RESET    (uint8_t)90
#define WRITE_PARAMETER_INDEX__CONFIG_SAVE_ACK    (uint8_t)91
#define WRITE_PARAMETER_INDEX__IMU_CALIBRATE_ACK    (uint8_t)92
#define WRITE_PARAMETER_INDEX__MP_RESET_ACK    (uint8_t)93
#define WRITE_PARAMETER_INDEX__FRAME_ID    (uint8_t)94
#define WRITE_PARAMETER_INDEX__WRITE_PARAMETER_INDEX    (uint8_t)95
#define WRITE_PARAMETER_INDEX__WRITE_PARAMETER_ACK    (uint8_t)96



void IMU_CONFIG_REG_A_callback();
void IMU_CONFIG_REG_B_callback();
void IMU_CONFIG_WRITE_ENABLE_callback();
void MD_THRESHOLD_TYPE_callback();
void MD_ACCEL_X_THRESHOLD_LOW_callback();
void MD_ACCEL_X_THRESHOLD_HIGH_callback();
void MD_ACCEL_Y_THRESHOLD_LOW_callback();
void MD_ACCEL_Y_THRESHOLD_HIGH_callback();
void MD_ACCEL_Z_THRESHOLD_LOW_callback();
void MD_ACCEL_Z_THRESHOLD_HIGH_callback();
void MD_GYRO_X_THRESHOLD_LOW_callback();
void MD_GYRO_X_THRESHOLD_HIGH_callback();
void MD_GYRO_Y_THRESHOLD_LOW_callback();
void MD_GYRO_Y_THRESHOLD_HIGH_callback();
void MD_GYRO_Z_THRESHOLD_LOW_callback();
void MD_GYRO_Z_THRESHOLD_HIGH_callback();
void MD_ROLL_THRESHOLD_LOW_callback();
void MD_ROLL_THRESHOLD_HIGH_callback();
void MD_PITCH_THRESHOLD_LOW_callback();
void MD_PITCH_THRESHOLD_HIGH_callback();
void MD_YAW_THRESHOLD_LOW_callback();
void MD_YAW_THRESHOLD_HIGH_callback();
void MP_ROLL_FILTER_CONSTANT_callback();
void MP_PITCH_FILTER_CONSTANT_callback();
void MP_YAW_FILTER_CONSTANT_callback();
void MD_WRITE_CONFIG_callback();
void LED_MODE_CONFIG_callback();
void LED_UC_WRITE_callback();
void CONTROL_callback();
void UPDATE_NODE_DATA_callback();

#endif /* ADCP_RECEIVE_H_ */
